import Foundation

extension MockWordOfDay {
    /// Which orientação mood states each Word of the Day passage speaks to,
    /// keyed by the English catalog's reference (matched across languages by
    /// `IntentionVerse.signature`). Hand-made from each passage and its
    /// context; 1 to 3 states per passage. A few passages are left out on
    /// purpose, and the Sermon on the Mount's warnings are never offered to
    /// guilt, anger or doubt: for someone who writes how they feel, they read as
    /// condemnation.
    static let moodStatesByEnglishReference: [String: [String]] = [
        "John 3:14-15": ["hopeful", "forgiven"],
        "Matthew 5:3": ["hopeful", "empty"],
        "Matthew 5:4": ["grief", "lonely"],
        "Matthew 5:5": ["peace", "angry"],
        "Matthew 5:6": ["empty", "hopeful"],
        "Matthew 5:7": ["forgiven", "angry"],
        "Matthew 5:8": ["hopeful"],
        "Matthew 5:9": ["peace", "angry"],
        "Matthew 5:10": ["steadfast", "hopeful"],
        "Matthew 5:11": ["steadfast", "lonely"],
        "Matthew 5:12": ["joyful"],
        "Matthew 5:13": ["steadfast"],
        "Matthew 5:14": ["steadfast"],
        "Matthew 5:15": ["joyful"],
        "Matthew 5:16": ["joyful", "steadfast"],
        "Matthew 5:18": ["steadfast"],
        "Matthew 5:19": ["steadfast"],
        "Matthew 5:23": ["angry"],
        "Matthew 5:24": ["angry", "forgiven"],
        "Matthew 6:6": ["dryness", "lonely"],
        "Matthew 6:8": ["anxious", "dryness"],
        "Matthew 6:19": ["empty"],
        "Matthew 6:20": ["empty", "hopeful"],
        "Matthew 6:21": ["empty"],
        "Matthew 6:24": ["steadfast"],
        "Matthew 6:26": ["anxious", "hopeful", "grateful"],
        "Matthew 6:33": ["anxious"],
        "Matthew 6:34": ["anxious", "tired"],
        "Matthew 7:1": ["angry"],
        "Matthew 7:2": ["angry"],
        "Matthew 7:7": ["dryness", "hopeful"],
        "Matthew 7:8": ["dryness", "hopeful"],
        "Matthew 7:9": ["loved", "dryness"],
        "Matthew 7:10": ["loved"],
        "Matthew 7:11": ["loved", "grateful", "dryness"],
        "Matthew 7:12": ["loved"],
        "Matthew 7:13": ["steadfast"],
        "Matthew 7:14": ["steadfast"],
        "Mark 10:27": ["hopeful", "doubtful", "tired"],
        "Luke 6:36": ["angry", "forgiven"],
        "John 13:34": ["loved", "lonely"],
        "John 14:27": ["peace", "anxious"],
        "Psalm 23:1": ["peace", "grateful", "lonely"],
        "Psalm 27:1": ["anxious", "hopeful"],
        "Psalm 62:2": ["peace", "steadfast"],
        "Psalm 121:1-2": ["anxious", "tired"],
        "Psalm 130:1-2": ["guilty", "grief", "dryness"],
        "Psalm 91:1": ["peace", "anxious"],
        "Isaiah 43:1": ["doubtful", "lonely", "anxious"],
        "Isaiah 55:6": ["dryness", "guilty"],
        "Isaiah 40:31": ["tired", "hopeful"],
        "Isaiah 58:11": ["dryness", "empty", "tired"],
        "Jeremiah 17:7": ["steadfast", "hopeful"],
        "Zephaniah 3:17": ["loved", "joyful"],
        "Ezekiel 37:5": ["empty", "hopeful", "grief"],
        "Romans 8:38-39": ["loved", "grief", "grateful"],
        "Romans 12:12": ["hopeful", "steadfast"],
        "Romans 15:13": ["hopeful", "peace", "doubtful"],
        "Galatians 5:22-23": ["joyful", "peace"],
        "1 Corinthians 13:4": ["loved", "angry"],
        "2 Corinthians 4:16": ["tired", "steadfast"],
        "James 1:5": ["doubtful"],
        "Hebrews 4:16": ["guilty", "forgiven", "dryness"],
        "Acts 1:8": ["steadfast"],
        "Acts 3:19": ["forgiven", "guilty"],
        "Acts 13:52": ["joyful"],
        "Acts 15:11": ["forgiven", "grateful", "guilty"],
        "Revelation 21:4": ["grief", "hopeful"],
    ]
}
