# -*- coding: utf-8 -*-
"""Bloco 1a — estados de consolação: peace e grateful.

Conteúdo editorial próprio. O texto bíblico NÃO está aqui: `ref` aponta o
capítulo e o versículo na numeração de cada edição, e build_exam_relief.py
extrai o texto de lá. Quando as duas edições dividem o versículo de forma
diferente, cada idioma declara o seu `ref` — é o caso de Salmo 12 na ansiedade.

`saintSource` registra a classe de fonte do fato biográfico. Como em todo o
resto do acervo, isso ainda pede conferência antes de publicar.
"""

VAT = "Biografia: vatican.va (a conferir)."


def r(saint, pt_ref, en_ref, pt, en, *, pt_saint, en_saint, pt_why, en_why, pt_step, en_step,
      pt_title, en_title, source=VAT):
    """Uma resposta, nos dois idiomas."""
    return {
        "saintID": saint,
        "pt": {"ref": pt_ref, "title": pt_title, "psalmWhy": pt, "saintName": pt_saint,
               "saintWhy": pt_why, "stepTitle": "Um passo concreto", "stepBody": pt_step,
               "saintSource": source},
        "en": {"ref": en_ref, "title": en_title, "psalmWhy": en, "saintName": en_saint,
               "saintWhy": en_why, "stepTitle": "A concrete step", "stepBody": en_step,
               "saintSource": source},
    }


BLOCK = {
    "peace": [
        r("teresa-avila", (22, (1,)), (22, (1,)),
          "O salmo não diz que nada falta porque tudo deu certo: diz que nada falta porque alguém conduz.",
          "The psalm does not say nothing is lacking because everything went well: it says nothing is lacking because someone is leading.",
          pt_title="Nada me falta", en_title="I shall want nothing",
          pt_saint="Santa Teresa de Ávila", en_saint="Saint Teresa of Ávila",
          pt_why="Escreveu sobre os graus da oração a partir da própria experiência, dentro de uma vida de reformas e viagens difíceis.",
          en_why="She wrote about the degrees of prayer out of her own experience, in the middle of a life of reforms and hard journeys.",
          pt_step="Antes da próxima tarefa, fique um minuto em silêncio sem apressar a passagem.",
          en_step="Before your next task, stay silent for one minute without rushing the transition."),

        r("francisco-assis", (4, (9,)), (4, (9,)),
          "O sono do salmista não vem de ter resolvido o dia: vem de saber quem o põe em segurança.",
          "The psalmist's sleep does not come from having settled the day: it comes from knowing who keeps him safe.",
          pt_title="Deitar em paz", en_title="Lying down in peace",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Fez da saudação \"o Senhor vos dê a paz\" a abertura de todo encontro, e a deixou escrita no seu Testamento.",
          en_why="He made \"the Lord give you peace\" the opening of every encounter, and left it written in his Testament.",
          pt_step="Termine o dia dizendo essa saudação a alguém de casa, em voz alta.",
          en_step="End the day by saying that greeting out loud to someone at home."),

        r("benito", (118, (165,)), (118, (165,)),
          "A paz aqui não é ausência de esforço: é o fruto de amar uma regra e não tropeçar nela.",
          "Peace here is not the absence of effort: it is the fruit of loving a rule and not stumbling over it.",
          pt_title="A paz de quem tem regra", en_title="The peace of having a rule",
          pt_saint="São Bento", en_saint="Saint Benedict",
          pt_why="Organizou a vida monástica ocidental em torno de oração, trabalho e estabilidade, numa regra escrita para ser vivida por gente comum.",
          en_why="He organized Western monastic life around prayer, work and stability, in a rule written to be lived by ordinary people.",
          pt_step="Escolha um horário fixo de oração para amanhã e escreva-o onde você vai ver.",
          en_step="Pick one fixed hour of prayer for tomorrow and write it where you will see it."),

        r("isabel-trindade", (90, (1,)), (90, (1,)),
          "Morar à sombra não é estar escondido do mundo: é estar coberto enquanto se atravessa.",
          "To dwell in the shadow is not to be hidden from the world: it is to be covered while crossing it.",
          pt_title="À sombra do Altíssimo", en_title="In the shadow of the Most High",
          pt_saint="Santa Isabel da Trindade", en_saint="Saint Elizabeth of the Trinity",
          pt_why="Carmelita de Dijon, escreveu sobre habitar em Deus como num lugar, e morreu aos 26 anos depois de meses de doença.",
          en_why="A Carmelite of Dijon, she wrote about dwelling in God as in a place, and died at 26 after months of illness.",
          pt_step="Repita uma frase curta deste salmo ao entrar em casa hoje.",
          en_step="Repeat one short line of this psalm as you walk into your home today."),

        r("jose", (130, (2,)), (130, (2,)),
          "O salmista não pede que a alma se acalme sozinha: ele mesmo a acalma, como se pega uma criança no colo.",
          "The psalmist does not ask his soul to settle by itself: he quiets it himself, the way one takes up a child.",
          pt_title="Como um menino no colo", en_title="Like a child at rest",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Nos Evangelhos ele recebe Maria e Jesus sob seus cuidados e age conforme o que lhe é indicado em sonho, sem uma palavra registrada.",
          en_why="In the Gospels he takes Mary and Jesus into his care and acts on what he is shown in a dream, without a single recorded word.",
          pt_step="Faça hoje uma coisa em silêncio por alguém de casa, sem comentar.",
          en_step="Do one thing in silence for someone at home today, without mentioning it."),

        r("joao-cruz", (61, (2,)), (61, (2,)),
          "Repousar em Deus é dito aqui como fonte da salvação, não como recompensa por ela.",
          "Resting in God is spoken of here as the source of salvation, not as a reward for it.",
          pt_title="Só em Deus", en_title="In God alone",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Escreveu sobre a noite escura durante e depois de nove meses preso por seus próprios irmãos de ordem em Toledo.",
          en_why="He wrote about the dark night during and after nine months imprisoned by his own brothers in religion at Toledo.",
          pt_step="Nomeie por escrito uma coisa que você está tentando segurar sozinho.",
          en_step="Write down one thing you are trying to hold up on your own."),

        r("clara-assis", (120, (7,)), (120, (7,)),
          "A guarda prometida é da alma, não das circunstâncias — e é isso que o salmo repete.",
          "The keeping promised here is of the soul, not of circumstances — and that is what the psalm repeats.",
          pt_title="Ele guarda a tua alma", en_title="He keeps your soul",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Fundou as Clarissas e permaneceu em São Damião por mais de quarenta anos, boa parte deles doente.",
          en_why="She founded the Poor Clares and stayed at San Damiano for more than forty years, much of it in illness.",
          pt_step="Deixe o telefone em outro quarto durante a próxima meia hora.",
          en_step="Leave your phone in another room for the next half hour."),

        r("filipe-neri", (33, (9,)), (33, (9,)),
          "O salmo manda provar antes de concluir: a bondade de Deus é apresentada como experiência, não como argumento.",
          "The psalm tells you to taste before concluding: God's goodness is offered as experience, not as argument.",
          pt_title="Gostai e vede", en_title="Taste and see",
          pt_saint="São Filipe Néri", en_saint="Saint Philip Neri",
          pt_why="Reuniu gente em Roma para oração, música e conversa, e é lembrado pelo bom humor no meio da direção espiritual.",
          en_why="He gathered people in Rome for prayer, music and conversation, and is remembered for good humour in the middle of spiritual direction.",
          pt_step="Convide alguém para rezar com você cinco minutos hoje.",
          en_step="Invite someone to pray with you for five minutes today."),

        r("tomas-aquino", (15, (5,)), (15, (5,)),
          "Chamar Deus de \"porção da herança\" é dizer que a segurança está em quem se tem, não no que se acumulou.",
          "Calling God \"the portion of my inheritance\" says that security lies in whom you have, not in what you have gathered.",
          pt_title="A porção da herança", en_title="The portion of my inheritance",
          pt_saint="São Tomás de Aquino", en_saint="Saint Thomas Aquinas",
          pt_why="Dominicano e doutor da Igreja, interrompeu a Suma Teológica no fim da vida e não voltou a escrevê-la.",
          en_why="A Dominican and Doctor of the Church, he broke off the Summa Theologiae near the end of his life and never resumed it.",
          pt_step="Escolha uma coisa que você tem e não precisa, e separe hoje para doar.",
          en_step="Pick one thing you own and do not need, and set it aside today to give away."),

        r("notburga", (36, (7,)), (36, (7,)),
          "O descanso do salmo vem junto de uma ordem: não se exasperar comparando o próprio caminho com o de quem prospera.",
          "The psalm's rest comes with an instruction: do not fret by comparing your own road with the road of those who prosper.",
          pt_title="Descansa e não te compares", en_title="Rest, and do not compare",
          pt_saint="Santa Notburga de Eben", en_saint="Saint Notburga of Eben",
          pt_why="Serva no Tirol, é lembrada por insistir em parar o trabalho no toque do sino da tarde, contra a ordem do patrão.",
          en_why="A servant in the Tyrol, she is remembered for insisting on stopping work at the evening bell, against her master's order.",
          pt_step="Pare o trabalho hoje na hora que você definiu, mesmo com coisa pendente.",
          en_step="Stop working today at the hour you set, even with something unfinished."),

        r("monica", (84, (9,)), (84, (9,)),
          "O salmista se põe primeiro a ouvir, e é ouvindo que descobre que Deus fala de paz.",
          "The psalmist sets himself to listen first, and it is in listening that he finds God speaking peace.",
          pt_title="Ouvir o que ele diz", en_title="Hearing what he says",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Acompanhou o filho Agostinho por décadas até a conversão dele, e morreu em Óstia pouco depois.",
          en_why="She followed her son Augustine for decades until his conversion, and died at Ostia soon after.",
          pt_step="Antes de responder a alguém hoje, conte até três em silêncio.",
          en_step="Before answering anyone today, count to three in silence."),

        r("andre-bessette", (45, (2,)), (45, (2,)),
          "O refúgio do salmo é declarado em meio às angústias, não depois que elas passam.",
          "The psalm's refuge is declared in the middle of troubles, not after they pass.",
          pt_title="Refúgio nas angústias", en_title="A refuge in trouble",
          pt_saint="Santo André Bessette", en_saint="Saint André Bessette",
          pt_why="Religioso da Congregação de Santa Cruz, foi porteiro em Montreal por quarenta anos e recebia os doentes na portaria.",
          en_why="A brother of the Congregation of Holy Cross, he was a porter in Montreal for forty years and received the sick at the door.",
          pt_step="Atenda hoje uma pessoa que você costuma deixar para depois.",
          en_step="Attend to one person today whom you usually put off."),

        r("teresinha", (138, (1,)), (138, (1,)),
          "Ser sondado e conhecido é apresentado aqui como consolo, não como ameaça.",
          "Being searched and known is offered here as consolation, not as threat.",
          pt_title="Tu me conheces", en_title="You have known me",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Descreveu a pequena via como caminho de confiança em gestos comuns, e morreu de tuberculose aos 24 anos.",
          en_why="She described the little way as a path of confidence in ordinary gestures, and died of tuberculosis at 24.",
          pt_step="Escolha hoje um gesto pequeno que ninguém vai notar, e faça-o bem.",
          en_step="Choose one small gesture today that nobody will notice, and do it well."),

        r("luis-gonzaga", (26, (1,)), (26, (1,)),
          "A pergunta \"a quem temerei\" não nega o medo: ela o coloca diante de alguém maior.",
          "The question \"whom shall I fear\" does not deny fear: it sets it before someone greater.",
          pt_title="Minha luz e salvação", en_title="My light and my salvation",
          pt_saint="São Luís Gonzaga", en_saint="Saint Aloysius Gonzaga",
          pt_why="Jesuíta de família nobre, morreu aos 23 anos depois de cuidar de doentes na peste de Roma.",
          en_why="A Jesuit from a noble family, he died at 23 after caring for the sick in the Roman plague.",
          pt_step="Nomeie em voz alta um medo concreto de hoje, e só isso.",
          en_step="Name one concrete fear from today out loud, and leave it at that."),

        r("carlo-acutis", (102, (1,)), (102, (1,)),
          "O salmista manda a própria alma bendizer: a gratidão aqui começa por decisão, não por sentimento.",
          "The psalmist commands his own soul to bless: gratitude here begins as a decision, not as a feeling.",
          pt_title="Bendiz, ó minha alma", en_title="Bless the Lord, O my soul",
          pt_saint="São Carlo Acutis", en_saint="Saint Carlo Acutis",
          pt_why="Adolescente italiano, catalogou milagres eucarísticos num site que montou ele mesmo, e morreu de leucemia aos 15 anos.",
          en_why="An Italian teenager, he catalogued Eucharistic miracles on a website he built himself, and died of leukaemia at 15.",
          pt_step="Escreva três coisas de hoje pelas quais você bendiz, mesmo sem sentir.",
          en_step="Write three things from today you bless God for, even without feeling it."),
    ],

    "grateful": [
        r("francisco-assis", (102, (2,)), (102, (2,)),
          "O salmo junta bendizer e não esquecer: a gratidão aqui é trabalho de memória.",
          "The psalm joins blessing and not forgetting: gratitude here is a work of memory.",
          pt_title="Não esquecer os benefícios", en_title="Forget not his benefits",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Compôs o Cântico das Criaturas já doente e quase cego, no fim da vida.",
          en_why="He composed the Canticle of the Creatures already ill and nearly blind, at the end of his life.",
          pt_step="Anote um benefício deste ano que você já tinha esquecido.",
          en_step="Write down one benefit from this year you had already forgotten."),

        r("josefina-bakhita", (106, (1,)), (106, (1,)),
          "O salmo dá a razão do louvor antes do louvor: porque a misericórdia é eterna, e não porque o dia foi bom.",
          "The psalm gives the reason for praise before the praise: because his mercy endures, not because the day went well.",
          pt_title="Porque a misericórdia é eterna", en_title="For his mercy endures",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Sequestrada no Sudão e escravizada por anos, tornou-se canossiana na Itália e viveu como porteira do convento em Schio.",
          en_why="Kidnapped in Sudan and enslaved for years, she became a Canossian in Italy and lived as the convent's doorkeeper at Schio.",
          pt_step="Agradeça hoje, olhando nos olhos, a alguém que faz um serviço invisível para você.",
          en_step="Thank someone today, looking them in the eye, for a service they do for you unseen."),

        r("teresinha", (117, (1,)), (117, (1,)),
          "Dar graças aparece aqui como ato público, dito em voz alta, e não como sentimento interior.",
          "Giving thanks appears here as a public act, said out loud, not as an inward feeling.",
          pt_title="Dai graças ao Senhor", en_title="Give thanks to the Lord",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Pediu que sua vida fosse recebida como oferta em gestos pequenos, e registrou isso no manuscrito escrito por obediência.",
          en_why="She asked that her life be received as an offering in small gestures, and set this down in the manuscript she wrote under obedience.",
          pt_step="Diga a alguém hoje, em voz alta, uma coisa boa que ele fez e você nunca mencionou.",
          en_step="Tell someone out loud today about one good thing they did that you never mentioned."),

        r("damiao-molokai", (99, (2,)), (99, (2,)),
          "O salmo manda servir com alegria: a alegria vem descrita como modo de servir, não como prêmio.",
          "The psalm commands serving with gladness: joy is described as a way of serving, not as a prize.",
          pt_title="Servir com alegria", en_title="Serve with gladness",
          pt_saint="São Damião de Molokai", en_saint="Saint Damien of Molokai",
          pt_why="Padre belga, viveu dezesseis anos entre os doentes de hanseníase em Molokai e morreu da mesma doença.",
          en_why="A Belgian priest, he lived sixteen years among the lepers of Molokai and died of the same disease.",
          pt_step="Faça hoje com cuidado a tarefa que você costuma fazer resmungando.",
          en_step="Do today, with care, the chore you usually do while complaining."),

        r("catarina-siena", (137, (1,)), (137, (1,)),
          "O louvor do salmista tem motivo dado: porque as palavras da sua boca foram ouvidas.",
          "The psalmist's praise has a stated reason: because the words of his mouth were heard.",
          pt_title="Porque me ouviste", en_title="Because you heard me",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Dominicana leiga, ditou centenas de cartas e interveio publicamente no retorno do papa de Avinhão a Roma.",
          en_why="A Dominican laywoman, she dictated hundreds of letters and intervened publicly in the pope's return from Avignon to Rome.",
          pt_step="Releia um pedido antigo seu que foi atendido, e agradeça por ele hoje.",
          en_step="Reread one old request of yours that was answered, and thank God for it today."),

        r("inacio-loyola", (33, (2,)), (33, (2,)),
          "\"Em todo o tempo\" é o ponto: o salmo não reserva o louvor para os dias bons.",
          "\"At all times\" is the point: the psalm does not reserve praise for the good days.",
          pt_title="Em todo o tempo", en_title="At all times",
          pt_saint="Santo Inácio de Loyola", en_saint="Saint Ignatius of Loyola",
          pt_why="Escreveu os Exercícios Espirituais a partir da própria convalescença depois de ser ferido em Pamplona.",
          en_why="He wrote the Spiritual Exercises out of his own convalescence after being wounded at Pamplona.",
          pt_step="Faça o exame do dia hoje começando pela gratidão, antes de qualquer outra coisa.",
          en_step="Make today's examen starting with gratitude, before anything else."),

        r("maria-madalena", (29, (12,)), (29, (12,)),
          "O salmo fala de pranto convertido em dança: a gratidão nasce de uma mudança que já aconteceu.",
          "The psalm speaks of mourning turned into dancing: gratitude here rises from a change that already happened.",
          pt_title="O pranto em dança", en_title="Mourning into dancing",
          pt_saint="Santa Maria Madalena", en_saint="Saint Mary Magdalene",
          pt_why="Os Evangelhos a põem junto à cruz, ao sepulcro, e como a primeira a anunciar a Ressurreição aos discípulos.",
          en_why="The Gospels place her at the cross, at the tomb, and as the first to announce the Resurrection to the disciples.",
          pt_step="Conte a alguém hoje uma coisa que melhorou na sua vida e você não comentou.",
          en_step="Tell someone today about one thing that got better in your life and you never mentioned."),

        r("vicente-paulo", (144, (1,)), (144, (1,)),
          "O salmista exalta a Deus como rei e promete bendizer \"pelos séculos\": a gratidão aqui tem prazo longo.",
          "The psalmist extols God as king and promises to bless him \"for ever\": gratitude here has a long horizon.",
          pt_title="Eu te exaltarei", en_title="I will extol you",
          pt_saint="São Vicente de Paulo", en_saint="Saint Vincent de Paul",
          pt_why="Organizou em França o socorro a pobres e expostos, e fundou a Congregação da Missão e as Filhas da Caridade.",
          en_why="In France he organized relief for the poor and for abandoned children, and founded the Congregation of the Mission and the Daughters of Charity.",
          pt_step="Separe hoje uma quantia pequena e fixa para dar este mês.",
          en_step="Set aside today a small fixed amount to give this month."),

        r("joao-bosco", (149, (1,)), (149, (1,)),
          "O cântico novo do salmo é cantado na assembleia: a gratidão aparece como coisa feita junto.",
          "The psalm's new song is sung in the assembly: gratitude appears as something done together.",
          pt_title="Um cântico novo", en_title="A new song",
          pt_saint="São João Bosco", en_saint="Saint John Bosco",
          pt_why="Reuniu meninos pobres em Turim em oratórios com escola, oficina e música, e fundou os Salesianos.",
          en_why="He gathered poor boys in Turin into oratories with school, workshop and music, and founded the Salesians.",
          pt_step="Cante ou ouça com atenção um canto da Missa hoje, do começo ao fim.",
          en_step="Sing or listen through one hymn from Mass today, start to finish."),

        r("martinho-tours", (135, (1,)), (135, (1,)),
          "O salmo repete a mesma razão da bondade divina como refrão, e é o refrão que educa a memória.",
          "The psalm repeats the same reason for God's goodness as a refrain, and it is the refrain that trains memory.",
          pt_title="Porque é bom", en_title="For he is good",
          pt_saint="São Martinho de Tours", en_saint="Saint Martin of Tours",
          pt_why="Soldado antes de bispo, é lembrado por partir o próprio manto para cobrir um pobre em Amiens.",
          en_why="A soldier before he was a bishop, he is remembered for cutting his own cloak to cover a poor man at Amiens.",
          pt_step="Dê hoje uma peça de roupa que você usa, não uma que você descartaria.",
          en_step="Give away today a piece of clothing you actually wear, not one you would discard."),

        r("antonio-padua", (91, (2,)), (91, (2,)),
          "Louvar é chamado de bom em si mesmo, antes de ser útil: é essa a afirmação do versículo.",
          "Praising is called good in itself, before being useful: that is the verse's claim.",
          pt_title="Bom é louvar", en_title="It is good to give praise",
          pt_saint="Santo Antônio de Pádua", en_saint="Saint Anthony of Padua",
          pt_why="Pregou na Itália e no sul da França e foi reconhecido pela tradição franciscana pelo estudo das Escrituras.",
          en_why="He preached in Italy and southern France and was recognized in the Franciscan tradition for his study of Scripture.",
          pt_step="Reserve dez minutos hoje para oração que não pede nada.",
          en_step="Set aside ten minutes today for prayer that asks for nothing."),

        r("clara-assis", (65, (1,)), (65, (1,)),
          "A aclamação é dirigida a todos os habitantes da terra: o salmo não trata a gratidão como assunto privado.",
          "The shout is addressed to all the earth: the psalm does not treat gratitude as a private matter.",
          pt_title="Aclamai, toda a terra", en_title="Shout with joy, all the earth",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Recusou repetidamente qualquer renda fixa para o seu mosteiro e obteve a aprovação da sua regra dois dias antes de morrer.",
          en_why="She repeatedly refused any fixed income for her monastery and obtained approval of her rule two days before she died.",
          pt_step="Agradeça hoje por uma coisa que você não escolheu e recebeu de graça.",
          en_step="Give thanks today for one thing you did not choose and received for free."),

        r("isabel-trindade", (110, (1,)), (110, (1,)),
          "O louvor é feito \"com todo o coração\" e na reunião dos justos: interior e comunitário na mesma frase.",
          "The praise is given \"with my whole heart\" and in the council of the just: inward and communal in the same line.",
          pt_title="Com todo o coração", en_title="With my whole heart",
          pt_saint="Santa Isabel da Trindade", en_saint="Saint Elizabeth of the Trinity",
          pt_why="Entrou no Carmelo de Dijon aos 21 anos e escreveu suas páginas mais conhecidas nos últimos meses de doença.",
          en_why="She entered the Carmel of Dijon at 21 and wrote her best-known pages in her last months of illness.",
          pt_step="Vá hoje a uma oração comunitária, mesmo curta, em vez de rezar só.",
          en_step="Go to one communal prayer today, even a short one, instead of praying alone."),

        r("filipe-neri", (95, (1,)), (95, (1,)),
          "O salmo pede canto novo: a gratidão de hoje não é obrigada a repetir a fórmula de ontem.",
          "The psalm asks for a new song: today's gratitude is not obliged to repeat yesterday's formula.",
          pt_title="Cantai um cântico novo", en_title="Sing a new song",
          pt_saint="São Filipe Néri", en_saint="Saint Philip Neri",
          pt_why="Usou música e conversa leve como parte da formação em Roma, e daí nasceram os Oratórios.",
          en_why="He used music and light conversation as part of formation in Rome, and the Oratory grew out of it.",
          pt_step="Agradeça hoje com palavras suas, sem usar nenhuma oração decorada.",
          en_step="Give thanks today in your own words, using no memorized prayer."),

        r("monica", (68, (31,)), (68, (31,)),
          "O salmista promete glorificar com cântico e proclamar com ação de graças: duas coisas, não uma.",
          "The psalmist promises to praise with a canticle and to magnify with thanksgiving: two things, not one.",
          pt_title="Cântico e ação de graças", en_title="Canticle and thanksgiving",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Rezou pela conversão do filho durante décadas e chegou a vê-la antes de morrer, longe de casa.",
          en_why="She prayed for her son's conversion for decades and lived to see it, far from home.",
          pt_step="Reze hoje por alguém pelo qual você já rezou e desistiu.",
          en_step="Pray today for someone you once prayed for and gave up on."),
    ],
}
