# -*- coding: utf-8 -*-
"""Bloco 6 — desolação: anxious e angry.

`angry` dispara a tela de encaminhamento pastoral. Nenhum passo deste estado
promete que a raiva vai passar, nem manda "deixar ir": eles tratam de não agir
sobre ela, de nomeá-la, de levá-la à oração e de reparar o que já foi feito.
Nada de linguagem clínica.

Salmo 12 tem numeração diferente nas duas edições: o "até quando revolverei
ansiedade em minha alma" está em 12,3 no Matos Soares e em 12,2 no Douay.
"""

from exam_relief_content._shared import r

BLOCK = {
    "anxious": [
        r("teresa-avila", (93, (19,)), (93, (19,)),
          "O salmo não diz que as angústias diminuem: diz que, quando se multiplicam, as consolações chegam junto.",
          "The psalm does not say the sorrows lessen: it says that when they multiply, the comforts come alongside.",
          pt_title="Quando se multiplicam", en_title="When they multiply",
          pt_saint="Santa Teresa de Ávila", en_saint="Saint Teresa of Ávila",
          pt_why="Fundou mosteiros sob suspeita da Inquisição e escrevia enquanto respondia a inquéritos sobre si mesma.",
          en_why="She founded monasteries under suspicion from the Inquisition, writing while answering inquiries about herself.",
          pt_step="Anote a preocupação principal e marque o que depende de você nas próximas horas.",
          en_step="Write down the main worry and mark what depends on you in the next few hours."),

        r("francisco-xavier", (54, (23,)), (54, (23,)),
          "O verbo do salmo é descarregar: o cuidado é tratado como peso que se transfere, não como ideia que se corrige.",
          "The psalm's verb is to cast: the care is treated as a weight transferred, not an idea corrected.",
          pt_title="Descarrega sobre ele", en_title="Cast it upon him",
          pt_saint="São Francisco Xavier", en_saint="Saint Francis Xavier",
          pt_why="Atravessou o Índico em navios onde muitos morriam na travessia, e escreveu cartas descrevendo o medo.",
          en_why="He crossed the Indian Ocean in ships where many died on the voyage, and wrote letters describing the fear.",
          pt_step="Diga em voz alta uma coisa que você vai deixar de tentar controlar hoje.",
          en_step="Say out loud one thing you will stop trying to control today."),

        r("joao-cruz", (41, (6,)), (41, (6,)),
          "O salmista interroga a própria alma em vez de obedecer a ela: a pergunta \"por que te conturbas\" é dirigida para dentro.",
          "The psalmist questions his own soul instead of obeying it: \"why art thou sad\" is addressed inward.",
          pt_title="Por que te conturbas", en_title="Why are you troubled",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Fugiu do cárcere de Toledo por uma janela depois de nove meses preso, e continuou na mesma reforma.",
          en_why="He escaped the Toledo prison through a window after nine months, and stayed in the same reform.",
          pt_step="Escreva a pergunta que está te rondando, em forma de pergunta.",
          en_step="Write down the question circling you, as a question."),

        r("padre-pio", (55, (4,)), (55, (4,)),
          "A confiança do salmo é declarada para quando o temor chegar: é preparada antes, não sentida no momento.",
          "The psalm's trust is declared for when the fear comes: prepared beforehand, not felt in the moment.",
          pt_title="Quando o temor me invadir", en_title="When fear comes",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Dizia a quem o procurava ansioso que rezasse e não se agitasse, e ele mesmo vivia sob vigilância da Santa Sé.",
          en_why="He told anxious visitors to pray and not to fret, and himself lived under scrutiny from the Holy See.",
          pt_step="Decida agora uma frase curta para repetir quando o medo vier hoje.",
          en_step="Decide now one short line to repeat when the fear comes today."),

        r("monica", (85, (7,)), (85, (7,)),
          "O salmista clama porque será ouvido — a razão do clamor é a resposta esperada, não o tamanho da aflição.",
          "The psalmist calls because he will be heard — the reason for calling is the expected answer, not the size of the distress.",
          pt_title="Porque me ouvirás", en_title="Because you will hear",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Rezou pela mesma intenção durante quase trinta anos, sem sinal de resposta na maior parte desse tempo.",
          en_why="She prayed for the same intention for nearly thirty years, with no sign of an answer for most of them.",
          pt_step="Reze hoje pela sua preocupação sem pedir um prazo.",
          en_step="Pray about your worry today without asking for a deadline."),

        r("catarina-siena", (141, (3,)), (141, (3,)),
          "O salmista expõe a preocupação diante de Deus: o verbo é manifestar, não resolver.",
          "The psalmist pours out his trouble before God: the verb is to declare, not to solve.",
          pt_title="Exponho a minha angústia", en_title="I declare my trouble",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Ditava cartas a secretários porque escrevia com dificuldade, e assim tratava de assuntos graves em voz alta.",
          en_why="She dictated letters to secretaries because writing came hard to her, and so dealt with grave matters out loud.",
          pt_step="Diga a sua preocupação em voz alta, sozinho, uma vez só.",
          en_step="Say your worry out loud, alone, just once."),

        r("teresinha", (119, (1,)), (119, (1,)),
          "O salmo conta no passado: clamei, e ele me ouviu. É apresentado como memória, para servir agora.",
          "The psalm tells it in the past: I cried, and he heard me. It is offered as memory, to serve now.",
          pt_title="Clamei e ele ouviu", en_title="I cried and he heard",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Registrou por escrito medos concretos da infância e da vida no Carmelo, sem transformá-los em lição.",
          en_why="She set down in writing concrete fears from childhood and from Carmel, without turning them into a lesson.",
          pt_step="Lembre de uma aflição antiga que passou, e diga como acabou.",
          en_step="Recall one old distress that passed, and say how it ended."),

        r("jose", (36, (5,)), (36, (5,)),
          "O salmo manda encomendar o caminho e esperar: duas ações, e a segunda é não fazer nada por um tempo.",
          "The psalm bids committing the way and trusting: two actions, and the second is doing nothing for a while.",
          pt_title="Encomenda o teu caminho", en_title="Commit your way",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Mudou de país com a família por um aviso em sonho e voltou depois por outro, sem explicação registrada.",
          en_why="He changed country with his family on a warning in a dream and returned later on another, with no recorded explanation.",
          pt_step="Adie até amanhã uma decisão que você ia tomar hoje por aflição.",
          en_step="Put off until tomorrow one decision you were going to make today out of distress."),

        r("oscar-romero", (106, (6,)), (106, (6,)),
          "O salmo conta um clamor coletivo: \"clamaram\", no plural. A aflição é apresentada como coisa de muitos.",
          "The psalm recounts a collective cry: \"they cried\", in the plural. The distress is presented as many people's.",
          pt_title="E clamaram", en_title="And they cried",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Recebia semanalmente famílias de desaparecidos no arcebispado e organizou um escritório para atendê-las.",
          en_why="He received families of the disappeared weekly at the archbishopric and set up an office to attend to them.",
          pt_step="Pergunte hoje a alguém como ele está, e espere a resposta.",
          en_step="Ask someone today how they are, and wait for the answer."),

        r("edith-stein", (76, (2,)), (76, (2,)),
          "A voz sobe duas vezes no mesmo verso: o salmo repete o gesto de clamar, como quem insiste.",
          "The voice rises twice in the same verse: the psalm repeats the act of crying out, like someone insisting.",
          pt_title="A minha voz sobe", en_title="I cried with my voice",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Pediu por carta ao papa que falasse sobre a perseguição aos judeus, em 1933, e não obteve resposta pública.",
          en_why="In 1933 she wrote to the pope asking him to speak about the persecution of the Jews, and received no public answer.",
          pt_step="Escreva hoje a carta ou a mensagem que você tem evitado escrever.",
          en_step="Write today the letter or message you have been avoiding."),

        r("maximiliano-kolbe", (68, (2,)), (68, (2,)),
          "A imagem é de água no pescoço: o salmo descreve a aflição pelo ponto em que ela já chegou, sem estimar o resto.",
          "The image is water up to the soul: the psalm describes the distress by how far it has come, without estimating the rest.",
          pt_title="As águas ao pescoço", en_title="The waters come in",
          pt_saint="São Maximiliano Maria Kolbe", en_saint="Saint Maximilian Kolbe",
          pt_why="Foi preso duas vezes pela Gestapo, a segunda em 1941, e continuou a exercer o ministério dentro do campo.",
          en_why="He was arrested twice by the Gestapo, the second time in 1941, and went on exercising his ministry inside the camp.",
          pt_step="Faça hoje só a próxima coisa, e não a lista inteira.",
          en_step="Do only the next thing today, not the whole list."),

        r("rita-cassia", (87, (3,)), (87, (3,)),
          "O pedido é para que a oração chegue e o ouvido se incline: o salmo se ocupa do trajeto do pedido, não do resultado.",
          "The request is that the prayer arrive and the ear incline: the psalm attends to the journey of the asking, not the outcome.",
          pt_title="Chegue a ti", en_title="Let it come before you",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Pediu três vezes a entrada no mosteiro e foi recusada nas três, antes de ser finalmente recebida.",
          en_why="She asked three times to enter the monastery and was refused all three, before finally being received.",
          pt_step="Peça hoje a mesma coisa que você pediu ontem, sem mudar as palavras.",
          en_step="Ask today for the same thing you asked yesterday, without changing the words."),

        r("andre-bessette", (24, (17,)), (24, (17,)),
          "O salmo pede alívio nomeando as angústias no plural: são muitas, e ele as trata como conjunto a ser aliviado.",
          "The psalm asks for relief naming the troubles in the plural: they are many, and it treats them as one set to be eased.",
          pt_title="Alivia as angústias", en_title="Deliver me from my troubles",
          pt_saint="Santo André Bessette", en_saint="Saint André Bessette",
          pt_why="Recebia por dia dezenas de pessoas com problemas que não podia resolver, e rezava com cada uma.",
          en_why="He received dozens of people a day with problems he could not solve, and prayed with each one.",
          pt_step="Liste hoje as suas preocupações e risque as que não são suas.",
          en_step="List your worries today and cross out the ones that are not yours."),

        r("inacio-loyola", (12, (3,)), (12, (2,)),
          "O salmista pergunta até quando vai revolver a ansiedade na própria alma: ele nomeia o hábito de remoer.",
          "The psalmist asks how long he will take counsels in his soul, sorrow in his heart all the day: he names the habit of turning it over.",
          pt_title="Até quando revolverei", en_title="How long shall I take counsels",
          pt_saint="Santo Inácio de Loyola", en_saint="Saint Ignatius of Loyola",
          pt_why="Escreveu regras para distinguir o espírito que agita do que consola, a partir de meses observando isso em si.",
          en_why="He wrote rules to tell the spirit that agitates from the one that consoles, out of months observing it in himself.",
          pt_step="Marque um horário hoje para pensar no problema, e fora dele não pense.",
          en_step="Set one time today to think about the problem, and outside it do not."),

        r("luis-gonzaga", (30, (8,)), (30, (8,)),
          "O salmista se alegra porque Deus olhou para a sua miséria: o consolo vem de ter sido visto, não de ter sido resolvido.",
          "The psalmist rejoices because God regarded his humility: the comfort comes from having been seen, not from having been fixed.",
          pt_title="Olhaste para a minha miséria", en_title="You regarded my lowliness",
          pt_saint="São Luís Gonzaga", en_saint="Saint Aloysius Gonzaga",
          pt_why="Cuidou de doentes em hospitais de Roma durante a peste de 1591 e contraiu a doença nesse serviço.",
          en_why="He nursed the sick in Roman hospitals during the plague of 1591 and contracted the disease in that service.",
          pt_step="Conte hoje a uma pessoa a coisa que você acha pequena demais para contar.",
          en_step="Tell one person today the thing you think is too small to mention."),
    ],

    "angry": [
        r("agostinho", (4, (5,)), (4, (5,)),
          "O salmo não proíbe a ira: põe um limite — não pecar — e manda repensar no coração, deitado.",
          "The psalm does not forbid anger: it sets a limit — sin not — and tells you to think it over in your heart, in bed.",
          pt_title="Não queirais pecar", en_title="Be angry, and sin not",
          pt_saint="Santo Agostinho", en_saint="Saint Augustine",
          pt_why="Escreveu sobre o próprio temperamento em disputas e sobre as brigas com adversários que depois revisou.",
          en_why="He wrote about his own temper in disputes and about the quarrels with opponents that he later revised.",
          pt_step="Não responda hoje à mensagem que você quer responder agora.",
          en_step="Do not reply today to the message you want to reply to right now."),

        r("francisco-assis", (36, (8,)), (36, (8,)),
          "O salmo manda guardar-se da ira e deixar o furor, e diz por quê: exasperar-se faz mal a quem se exaspera.",
          "The psalm bids ceasing from anger and leaving rage, and says why: fretting harms the one who frets.",
          pt_title="Deixa o furor", en_title="Leave rage",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Foi afastado do governo da própria ordem enquanto ela crescia em direção diferente da que ele quis.",
          en_why="He was set aside from governing his own order while it grew in a direction other than the one he wanted.",
          pt_step="Saia da conversa hoje antes de dizer a última palavra.",
          en_step="Leave the conversation today before saying the last word."),

        r("joao-batista", (6, (2,)), (6, (2,)),
          "O salmista pede que Deus não o corrija na ira: ele sabe o que é ser tratado por alguém irado, e pede outra coisa.",
          "The psalmist asks God not to rebuke him in indignation: he knows what being handled in anger is, and asks for something else.",
          pt_title="Não na tua ira", en_title="Not in your indignation",
          pt_saint="São João Batista", en_saint="Saint John the Baptist",
          pt_why="Denunciou Herodes diretamente e foi preso por isso, sem mudar o que havia dito.",
          en_why="He denounced Herod directly and was imprisoned for it, without changing what he had said.",
          pt_step="Diga hoje a verdade que você precisa dizer, sem elevar a voz.",
          en_step="Say the truth you need to say today, without raising your voice."),

        r("edith-stein", (93, (3,)), (93, (3,)),
          "O salmo pergunta \"até quando\" sobre a impunidade dos ímpios: é uma oração de indignação, e está no Saltério.",
          "The psalm asks \"how long\" about the impunity of the wicked: a prayer of indignation, and it is in the Psalter.",
          pt_title="Até quando os ímpios", en_title="How long shall sinners",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Perdeu o posto universitário por uma lei racial em 1933 e escreveu sobre isso sem retórica de vingança.",
          en_why="She lost her university post to a racial law in 1933 and wrote about it without any rhetoric of revenge.",
          pt_step="Escreva hoje a injustiça que te revolta, com fatos e sem adjetivos.",
          en_step="Write down today the injustice that angers you, with facts and no adjectives."),

        r("oscar-romero", (139, (2,)), (139, (2,)),
          "O salmo pede livramento do homem malvado, não a sua destruição: o pedido é de proteção, não de troco.",
          "The psalm asks deliverance from the evil man, not his destruction: the request is protection, not payback.",
          pt_title="Livra-me do malvado", en_title="Deliver me from the evil man",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Pediu publicamente aos soldados que desobedecessem a ordens de matar, e foi assassinado no dia seguinte a essa homilia.",
          en_why="He publicly asked soldiers to disobey orders to kill, and was murdered the day after that homily.",
          pt_step="Peça proteção hoje, e não que a pessoa se dê mal.",
          en_step="Ask for protection today, and not for the person's ruin."),

        r("catarina-siena", (78, (5,)), (78, (5,)),
          "O salmo dirige a pergunta a Deus e sobre Deus: até quando permanecerás irado. A queixa é feita a quem se reza.",
          "The psalm puts the question to God and about God: how long wilt thou be angry. The complaint is made to the one prayed to.",
          pt_title="Até quando, Senhor", en_title="How long, O Lord",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Escreveu ao papa chamando-o de \"babbo mio\" e ao mesmo tempo exigindo dele coragem, no mesmo parágrafo.",
          en_why="She wrote to the pope calling him \"babbo mio\" while demanding courage of him, in the same paragraph.",
          pt_step="Reclame hoje na oração, com as palavras que você usaria de verdade.",
          en_step="Complain in prayer today, in the words you would actually use."),

        r("monica", (36, (1,)), (36, (1,)),
          "A ordem do salmo é não se irritar por causa dos malfeitores: a raiva é tratada como algo que se pode não alimentar.",
          "The psalm's command is not to be emulous of evildoers: anger is treated as something one can decline to feed.",
          pt_title="Não te irrites", en_title="Be not emulous",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Conviveu anos com um marido de temperamento violento sem revidar, e é lembrada por aconselhar outras mulheres sobre isso.",
          en_why="She lived for years with a husband of violent temper without retaliating, and is remembered for counselling other women about it.",
          pt_step="Pare hoje de acompanhar quem te irrita nas redes.",
          en_step="Stop following today the person who angers you online."),

        r("rita-cassia", (16, (1,)), (16, (1,)),
          "O salmista pede que Deus ouça uma causa justa: a raiva é levada como processo a ser julgado, não como sentença já dada.",
          "The psalmist asks God to hear his just cause: the anger is brought as a case to be judged, not a sentence already passed.",
          pt_title="Ouve uma causa justa", en_title="Hear my just cause",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Impediu que os filhos vingassem o assassinato do pai, numa região onde a vingança era esperada.",
          en_why="She kept her sons from avenging their father's murder, in a region where revenge was expected.",
          pt_step="Não conte hoje a terceiros a ofensa que você sofreu.",
          en_step="Do not tell a third party today about the offence you suffered."),

        r("pedro-paulo", (88, (47,)), (88, (47,)),
          "O salmo pergunta se Deus ficará escondido para sempre: a raiva aqui é com o silêncio dele, e é dita a ele.",
          "The psalm asks whether God will hide himself for ever: the anger here is at his silence, and it is said to him.",
          pt_title="Ficarás escondido", en_title="Will you hide yourself",
          pt_saint="São Paulo", en_saint="Saint Paul",
          pt_why="Escreveu que pediu três vezes para ser livrado de um espinho na carne e recebeu como resposta uma recusa.",
          en_why="He wrote that he asked three times to be freed from a thorn in the flesh and received a refusal for answer.",
          pt_step="Reze hoje mesmo estando com raiva de Deus, e diga isso a ele.",
          en_step="Pray today even while angry at God, and say so to him."),

        r("tomas-aquino", (72, (3,)), (72, (3,)),
          "O salmista confessa inveja da prosperidade dos ímpios: nomeia a raiz da raiva antes de tratá-la.",
          "The psalmist confesses zeal at the prosperity of the wicked: he names the root of the anger before treating it.",
          pt_title="Tive inveja", en_title="I had zeal",
          pt_saint="São Tomás de Aquino", en_saint="Saint Thomas Aquinas",
          pt_why="Distinguiu a ira que busca justiça da que busca vingança, tratando as duas como paixões diferentes.",
          en_why="He distinguished anger that seeks justice from anger that seeks revenge, treating them as different passions.",
          pt_step="Escreva hoje se você quer justiça ou quer que a pessoa pague.",
          en_step="Write down today whether you want justice or want the person to pay."),

        r("maximiliano-kolbe", (58, (2,)), (58, (2,)),
          "O pedido é de defesa contra os que se levantam: o salmo põe Deus entre o salmista e o adversário, não contra o adversário.",
          "The request is for defence against those who rise up: the psalm puts God between the psalmist and the adversary, not against him.",
          pt_title="Defende-me", en_title="Defend me",
          pt_saint="São Maximiliano Maria Kolbe", en_saint="Saint Maximilian Kolbe",
          pt_why="Foi morto em Auschwitz depois de se oferecer no lugar de outro prisioneiro, sem denunciar ninguém.",
          en_why="He died at Auschwitz after offering himself in place of another prisoner, denouncing no one.",
          pt_step="Proteja hoje alguém de um comentário que você poderia repetir.",
          en_step="Shield someone today from a remark you could have passed on."),

        r("jose", (34, (13,)), (34, (13,)),
          "O salmista conta que rezava por quem o afligia: o salmo registra a resposta que ele deu, não o sentimento que teve.",
          "The psalmist says he prayed for those who troubled him: the psalm records the response he gave, not the feeling he had.",
          pt_title="Vestia-me de cilício por eles", en_title="I was clothed with haircloth",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Podia repudiar Maria em público segundo a lei e decidiu não a expor, conforme o Evangelho de Mateus.",
          en_why="He could have repudiated Mary publicly under the law and decided not to expose her, according to Matthew's Gospel.",
          pt_step="Reze hoje pela pessoa com quem você está com raiva, pelo nome.",
          en_step="Pray today by name for the person you are angry with."),

        r("josefina-bakhita", (37, (10,)), (37, (10,)),
          "O salmo diz que o gemido não é oculto a Deus: a raiva não precisa ser bem formulada para ser ouvida.",
          "The psalm says the groaning is not hidden from God: the anger need not be well phrased to be heard.",
          pt_title="O meu gemido não te é oculto", en_title="My groaning is not hidden",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Foi marcada com cortes na pele por ordem de um dos donos, e descreveu isso em depoimento já religiosa.",
          en_why="She was cut and scarred on the orders of one of her owners, and described it in testimony given as a religious.",
          pt_step="Deixe a oração hoje ser só um som, se não vierem palavras.",
          en_step="Let your prayer today be only a sound, if no words come."),

        r("joao-cruz", (141, (3,)), (141, (3,)),
          "O salmista manifesta a angústia diante de Deus antes de qualquer pedido: a raiva é exposta, não argumentada.",
          "The psalmist declares his trouble before God before any request: the anger is set out, not argued.",
          pt_title="Manifesto a minha angústia", en_title="I declare my trouble",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Foi preso por irmãos da própria ordem e, depois de libertado, não escreveu nada contra eles pelo nome.",
          en_why="He was imprisoned by brothers of his own order and, once free, wrote nothing against them by name.",
          pt_step="Não nomeie hoje, em nenhuma conversa, quem te ofendeu.",
          en_step="Do not name today, in any conversation, the person who offended you."),

        r("vicente-paulo", (30, (10,)), (30, (10,)),
          "O salmo diz que os olhos definham de tristeza, e usa a palavra ira no mesmo verso: as duas coisas aparecem juntas.",
          "The psalm says the eye is troubled with wrath, and names sorrow in the same verse: the two appear together.",
          pt_title="Definham os meus olhos", en_title="My eye is troubled",
          pt_saint="São Vicente de Paulo", en_saint="Saint Vincent de Paul",
          pt_why="Era descrito pelos contemporâneos como de temperamento difícil na juventude, e trabalhou nisso a vida inteira.",
          en_why="Contemporaries described him as difficult in temperament when young, and he worked on it all his life.",
          pt_step="Peça hoje a alguém que te avise quando você levantar a voz.",
          en_step="Ask someone today to tell you when you raise your voice."),
    ],
}
