# -*- coding: utf-8 -*-
"""Bloco 7 — desolação: grief e dryness.

`grief` dispara a tela de encaminhamento pastoral. Nenhum passo deste estado
apressa o luto, promete que vai passar, nem propõe que a pessoa se recomponha:
eles tratam de nomear a perda, de não ficar só, e de continuar a rezar sem
exigir consolo. Nada de linguagem clínica.
"""

from exam_relief_content._shared import r

BLOCK = {
    "grief": [
        r("monica", (41, (4,)), (41, (4,)),
          "As lágrimas são chamadas de pão: no salmo, o luto não é interrupção da vida, é o que a alimenta por um tempo.",
          "The tears are called bread: in the psalm, grief is not an interruption of life but what feeds it for a while.",
          pt_title="As lágrimas, meu pão", en_title="My tears, my bread",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Chorou pelo filho durante anos, e é nomeada nas Confissões justamente pelas lágrimas.",
          en_why="She wept over her son for years, and is named in the Confessions precisely for the tears.",
          pt_step="Chore hoje, se vier, sem tentar parar.",
          en_step="Weep today, if it comes, without trying to stop."),

        r("maria-madalena", (6, (7,)), (6, (7,)),
          "O salmo conta que o leito é regado de lágrimas todas as noites: descreve a repetição, não o fim dela.",
          "The psalm says the bed is washed with tears every night: it describes the repetition, not its end.",
          pt_title="Todas as noites", en_title="Every night",
          pt_saint="Santa Maria Madalena", en_saint="Saint Mary Magdalene",
          pt_why="Foi ao sepulcro de madrugada, com os aromas, esperando encontrar um corpo.",
          en_why="She went to the tomb at daybreak, with the spices, expecting to find a body.",
          pt_step="Vá hoje ao lugar onde você sente mais falta da pessoa.",
          en_step="Go today to the place where you miss the person most."),

        r("rita-cassia", (30, (11,)), (30, (11,)),
          "A vida é dita consumida na dor e os anos em gemidos: o salmo mede o luto em anos, não em dias.",
          "Life is said to be wasted with grief and the years in sighs: the psalm measures mourning in years, not days.",
          pt_title="Os meus anos em gemidos", en_title="My years in sighs",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Perdeu o marido e, em seguida, os dois filhos, e só depois foi recebida no mosteiro.",
          en_why="She lost her husband and then both her sons, and only afterwards was received into the monastery.",
          pt_step="Não marque hoje um prazo para você estar melhor.",
          en_step="Do not set a date today for when you should be better."),

        r("jose-sanchez-del-rio", (129, (1,)), (129, (1,)),
          "O clamor do salmo vem do mais profundo: ele não pede que a pessoa suba primeiro para poder rezar.",
          "The psalm's cry comes out of the depths: it does not ask you to climb out first in order to pray.",
          pt_title="Desde o mais profundo", en_title="Out of the depths",
          pt_saint="São José Sánchez del Río", en_saint="Saint José Sánchez del Río",
          pt_why="Foi preso, torturado e morto aos catorze anos, em 1928, durante a perseguição religiosa no México.",
          en_why="He was taken, tortured and killed at fourteen, in 1928, during the religious persecution in Mexico.",
          pt_step="Reze hoje uma frase só, de onde você está.",
          en_step="Pray one line only today, from where you are."),

        r("edith-stein", (87, (19,)), (87, (19,)),
          "O verso termina sem consolo: os familiares são as trevas. O salmo permite que a oração acabe assim.",
          "The verse ends without comfort: darkness is his acquaintance. The psalm allows prayer to end that way.",
          pt_title="Sem consolo no fim do verso", en_title="No comfort at the verse's end",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Perdeu a mãe pouco antes de entrar no Carmelo e foi levada de lá com a irmã Rosa, morta com ela em 1942.",
          en_why="She lost her mother shortly before entering Carmel and was taken from there with her sister Rosa, killed with her in 1942.",
          pt_step="Deixe hoje a oração sem conclusão, se for o caso.",
          en_step="Leave your prayer today without a conclusion, if that is where it ends."),

        r("joao-paulo-ii", (33, (19,)), (33, (19,)),
          "O salmo diz que Deus está perto dos contritos: a proximidade é afirmada sem condição de estado de ânimo.",
          "The psalm says the Lord is nigh to the contrite: the nearness is stated with no condition of mood.",
          pt_title="Perto dos contritos", en_title="Nigh to the contrite",
          pt_saint="São João Paulo II", en_saint="Saint John Paul II",
          pt_why="Ficou órfão de mãe aos nove anos, perdeu o irmão aos doze e o pai aos vinte, antes de entrar no seminário.",
          en_why="He lost his mother at nine, his brother at twelve and his father at twenty, before entering the seminary.",
          pt_step="Conte hoje a alguém quem você perdeu, e o nome dela.",
          en_step="Tell someone today whom you lost, and their name."),

        r("damiao-molokai", (101, (4,)), (101, (4,)),
          "Os dias são ditos dissipados como fumo: o salmo nomeia a sensação de que o tempo não deixa marca.",
          "The days are said to vanish like smoke: the psalm names the sense that time leaves no mark.",
          pt_title="Como fumo", en_title="Like smoke",
          pt_saint="São Damião de Molokai", en_saint="Saint Damien of Molokai",
          pt_why="Enterrou com as próprias mãos centenas de doentes em Molokai e construiu os caixões de muitos deles.",
          en_why="He buried hundreds of the sick at Molokai with his own hands and built the coffins for many of them.",
          pt_step="Faça hoje uma coisa concreta pela memória de quem morreu.",
          en_step="Do one concrete thing today for the memory of the person who died."),

        r("teresinha", (55, (9,)), (55, (9,)),
          "As lágrimas são recolhidas e guardadas: o salmo trata o luto como coisa que alguém conserva, não descarta.",
          "The tears are gathered and kept: the psalm treats grief as something someone preserves, not discards.",
          pt_title="Recolhidas no teu odre", en_title="My tears in your sight",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Perdeu a mãe aos quatro anos e quatro irmãos antes de nascer, e escreveu sobre isso já adulta.",
          en_why="She lost her mother at four and four siblings before her birth, and wrote about it as an adult.",
          pt_step="Guarde hoje um objeto da pessoa em lugar visível.",
          en_step="Put one object of the person's somewhere visible today."),

        r("josefina-bakhita", (24, (16,)), (24, (16,)),
          "O salmista pede que Deus olhe porque está só e aflito: a solidão do luto é apresentada como razão do pedido.",
          "The psalmist asks God to look because he is alone and poor: grief's loneliness is the reason for the request.",
          pt_title="Só e aflito", en_title="Alone and afflicted",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Perdeu a família aos sete anos e nunca a reencontrou, nem soube o nome que lhe deram ao nascer.",
          en_why="She lost her family at seven and never found them again, nor learned the name they gave her at birth.",
          pt_step="Não fique hoje sozinho na hora em que dói mais.",
          en_step="Do not be alone today at the hour when it hurts most."),

        r("oscar-romero", (68, (21,)), (68, (21,)),
          "O salmo diz que o coração foi despedaçado e que ninguém se condoeu: registra também a ausência de consolo humano.",
          "The psalm says the heart was broken and no one was found to comfort: it records the absence of human comfort too.",
          pt_title="Esperei que alguém", en_title="I looked for one",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Enterrou padres e catequistas assassinados da própria diocese, e lia os nomes nas homilias.",
          en_why="He buried murdered priests and catechists from his own diocese, and read the names in his homilies.",
          pt_step="Peça hoje a uma pessoa que fique com você em silêncio.",
          en_step="Ask one person today to sit with you in silence."),

        r("clara-assis", (72, (26,)), (72, (26,)),
          "A carne e o coração desfalecem, e no mesmo verso Deus é chamado herança: o salmo põe as duas coisas juntas.",
          "The flesh and the heart faint away, and in the same verse God is called his portion: the psalm holds both together.",
          pt_title="Desfalece e permanece", en_title="Fainting, and yet",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Viu morrer Francisco, a quem seguia desde os dezoito anos, e viveu vinte e sete anos depois dele.",
          en_why="She saw the death of Francis, whom she had followed since she was eighteen, and lived twenty-seven years after him.",
          pt_step="Reze hoje uma oração que a pessoa que morreu rezava.",
          en_step="Pray today a prayer the person who died used to pray."),

        r("joao-cruz", (22, (4,)), (22, (4,)),
          "O vale é atravessado, não evitado: o salmo diz que se anda por dentro dele, e que não se anda só.",
          "The valley is walked through, not avoided: the psalm says you go inside it, and not alone.",
          pt_title="Ainda que eu ande", en_title="Though I should walk",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Escreveu sobre a noite da alma como travessia com destino, e morreu em Úbeda entre estranhos.",
          en_why="He wrote of the soul's night as a crossing with a destination, and died at Úbeda among strangers.",
          pt_step="Ande hoje um caminho que você fazia com a pessoa.",
          en_step="Walk today a route you used to walk with the person."),

        r("padre-pio", (37, (10,)), (37, (10,)),
          "O salmo diz que o gemido não está oculto a Deus: o luto não precisa ser dito em palavras para ser ouvido.",
          "The psalm says the groaning is not hidden from God: grief need not be put in words to be heard.",
          pt_title="O gemido não está oculto", en_title="My groaning is not hidden",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Ouvia por dia dezenas de pessoas em luto no confessionário e era descrito como econômico nas palavras.",
          en_why="He heard dozens of grieving people a day in the confessional and was described as sparing with words.",
          pt_step="Fique hoje cinco minutos em silêncio, sem formular nada.",
          en_step="Stay five minutes in silence today, forming nothing."),

        r("maximiliano-kolbe", (30, (10,)), (30, (10,)),
          "O salmo nomeia os olhos que definham e a alma em angústia: descreve o corpo do luto antes de pedir qualquer coisa.",
          "The psalm names the eye troubled and the soul afflicted: it describes grief's body before asking anything.",
          pt_title="Definham os meus olhos", en_title="My eye is troubled",
          pt_saint="São Maximiliano Maria Kolbe", en_saint="Saint Maximilian Kolbe",
          pt_why="Perdeu o pai executado pelos russos em 1914 e morreu ele mesmo num campo de concentração em 1941.",
          en_why="He lost his father, executed by the Russians in 1914, and died himself in a concentration camp in 1941.",
          pt_step="Reze hoje pelos mortos da sua família, pelos nomes.",
          en_step="Pray today for your family's dead, by name."),

        r("francisco-assis", (125, (5,)), (125, (5,)),
          "O salmo fala de semear entre lágrimas: não nega o choro, dá-lhe um destino que ainda não se vê.",
          "The psalm speaks of sowing in tears: it does not deny the weeping, it gives it an end not yet visible.",
          pt_title="Semear entre lágrimas", en_title="Sowing in tears",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Chamou a morte de irmã no Cântico das Criaturas, depois de acrescentar essa estrofe no fim da vida.",
          en_why="He called death a sister in the Canticle of the Creatures, adding that stanza at the end of his life.",
          pt_step="Plante hoje alguma coisa, ou cuide de uma planta que existe.",
          en_step="Plant something today, or tend a plant you already have."),
    ],

    "dryness": [
        r("joao-cruz", (62, (2,)), (62, (2,)),
          "O salmista busca desde a madrugada e declara a sede: a aridez é tratada como hora de buscar, não de parar.",
          "The psalmist watches at break of day and declares his thirst: the dryness is the hour to seek, not to stop.",
          pt_title="De ti está sedenta", en_title="For thee my soul thirsts",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Deu nome de noite escura à oração que não sente nada, e a descreveu como purificação, não castigo.",
          en_why="He named as dark night the prayer that feels nothing, and described it as purification, not punishment.",
          pt_step="Cumpra hoje o horário da oração e não avalie como ela foi.",
          en_step="Keep your prayer time today and do not judge how it went."),

        r("teresinha", (142, (6,)), (142, (6,)),
          "A alma é comparada a terra sem água e as mãos estão estendidas: o gesto continua mesmo sem o sentimento.",
          "The soul is likened to waterless ground and the hands are stretched out: the gesture continues without the feeling.",
          pt_title="Terra sem água", en_title="Earth without water",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Dormia na oração e escreveu que isso não a preocupava, porque médicos adormecem o paciente para operar.",
          en_why="She fell asleep at prayer and wrote that it did not trouble her, since doctors put patients to sleep to operate.",
          pt_step="Reze hoje sentado e sem exigir atenção perfeita.",
          en_step="Pray today seated and without demanding perfect attention."),

        r("teresa-avila", (83, (3,)), (83, (3,)),
          "A alma suspira e desfalece desejando os átrios do Senhor: no salmo o desejo persiste sem a experiência.",
          "The soul longs and faints for the courts of the Lord: in the psalm the desire persists without the experience.",
          pt_title="Desejando os átrios", en_title="Longing for the courts",
          pt_saint="Santa Teresa de Ávila", en_saint="Saint Teresa of Ávila",
          pt_why="Escreveu que passou quase vinte anos com a oração difícil e sem gosto, antes do que chamou de segunda conversão.",
          en_why="She wrote that she spent almost twenty years with prayer difficult and without relish, before what she called her second conversion.",
          pt_step="Vá hoje a uma igreja e fique lá dez minutos.",
          en_step="Go into a church today and stay ten minutes."),

        r("edith-stein", (118, (81,)), (118, (81,)),
          "O salmista diz que desfalece e, no mesmo verso, que espera na palavra: os dois estados coexistem.",
          "The psalmist says he faints and, in the same verse, that he hopes in the word: both states coexist.",
          pt_title="Desfaleço e espero", en_title="Fainting, and hoping",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Continuou a escrever filosofia dentro do Carmelo, inclusive nos meses em que sabia estar sob risco de deportação.",
          en_why="She kept writing philosophy inside Carmel, including in the months she knew she was at risk of deportation.",
          pt_step="Leia hoje um versículo e copie-o à mão.",
          en_step="Read one verse today and copy it by hand."),

        r("monica", (87, (10,)), (87, (10,)),
          "O salmo diz que os olhos desfalecem e que se clama todo o dia: a insistência é o que resta na aridez.",
          "The psalm says the eyes languish and that he cries all the day: the insisting is what remains in dryness.",
          pt_title="Clamo todo o dia", en_title="All the day I cried",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Manteve a mesma oração por décadas sem sinal de que estivesse sendo ouvida.",
          en_why="She kept the same prayer for decades with no sign that it was being heard.",
          pt_step="Reze hoje a mesma oração de ontem, sem variar.",
          en_step="Pray the same prayer as yesterday today, without varying it."),

        r("padre-pio", (101, (5,)), (101, (5,)),
          "O coração é dito ressequido como erva queimada: o salmo dá à aridez uma imagem física, sem explicá-la.",
          "The heart is called withered like smitten grass: the psalm gives dryness a physical image, without explaining it.",
          pt_title="Ressequido", en_title="Withered",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Escreveu em cartas sobre longos períodos sem consolo na oração, mantendo a rotina litúrgica do dia.",
          en_why="He wrote in letters about long periods without consolation in prayer, keeping the day's liturgical routine.",
          pt_step="Faça hoje a oração mais curta que você conhece, e só ela.",
          en_step="Pray the shortest prayer you know today, and only that."),

        r("catarina-siena", (30, (23,)), (30, (23,)),
          "O salmista confessa ter dito que foi expulso da presença de Deus: o salmo registra a conclusão errada que a aridez sugere.",
          "The psalmist confesses having said he was cast away from God's face: the psalm records the wrong conclusion dryness suggests.",
          pt_title="Eu disse na minha ansiedade", en_title="I said in the excess of my mind",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Descreveu um tempo em que se julgou abandonada, e a resposta que registrou foi que nunca estivera só.",
          en_why="She described a time in which she thought herself abandoned, and the answer she recorded was that she had never been alone.",
          pt_step="Não conclua hoje nada sobre a sua fé a partir do que você sente.",
          en_step="Draw no conclusion about your faith today from what you feel."),

        r("francisco-xavier", (76, (3,)), (76, (3,)),
          "O salmo diz que a mão se estende e não se cansa: o gesto é mantido, mesmo sem resposta descrita.",
          "The psalm says his hands were lifted up and he was not deceived: the gesture is kept, with no answer described.",
          pt_title="A mão estendida", en_title="With hands lifted up",
          pt_saint="São Francisco Xavier", en_saint="Saint Francis Xavier",
          pt_why="Escreveu cartas descrevendo meses de viagem sem consolo e sem companhia que falasse a sua língua.",
          en_why="He wrote letters describing months of travel without consolation and without company that spoke his language.",
          pt_step="Reze hoje de pé, com as mãos abertas, por dois minutos.",
          en_step="Pray standing today, hands open, for two minutes."),

        r("isabel-trindade", (41, (10,)), (41, (10,)),
          "O salmista chama Deus de rochedo e pergunta por que o esquece: a queixa é dirigida a quem ele ainda chama de apoio.",
          "The psalmist calls God his support and asks why he has forgotten him: the complaint is addressed to the one he still calls support.",
          pt_title="Por que te esqueces", en_title="Why have you forgotten me",
          pt_saint="Santa Isabel da Trindade", en_saint="Saint Elizabeth of the Trinity",
          pt_why="Escreveu sobre a presença de Deus na alma nos meses em que a doença de Addison lhe dava dores constantes.",
          en_why="She wrote about God's presence in the soul in the months when Addison's disease gave her constant pain.",
          pt_step="Pergunte hoje na oração o que você não ousa perguntar.",
          en_step="Ask in prayer today what you do not dare to ask."),

        r("carlo-acutis", (72, (21,)), (72, (21,)),
          "O salmo nomeia o espírito exasperado e o coração sentido: a aridez é dita sem ser justificada.",
          "The psalm names the heart inflamed and the reins changed: the dryness is stated without being justified.",
          pt_title="O espírito exasperado", en_title="My heart inflamed",
          pt_saint="São Carlo Acutis", en_saint="Saint Carlo Acutis",
          pt_why="Mantinha Missa diária e adoração desde os sete anos, e não deixou registro de fervor excepcional.",
          en_why="He kept daily Mass and adoration from the age of seven, and left no record of exceptional fervour.",
          pt_step="Vá hoje à adoração mesmo sem vontade, por dez minutos.",
          en_step="Go to adoration today even without wanting to, for ten minutes."),

        r("benito", (12, (2,)), (12, (2,)),
          "O salmo pergunta até quando Deus esconderá o rosto: a aridez é posta como pergunta, e é oração legítima.",
          "The psalm asks how long he will take counsels in his soul with sorrow all the day: dryness is put as a question, and it is legitimate prayer.",
          pt_title="Até quando esconderás", en_title="How long shall I take counsels",
          pt_saint="São Bento", en_saint="Saint Benedict",
          pt_why="Escreveu uma regra que manda rezar em horas fixas independentemente da disposição de quem reza.",
          en_why="He wrote a rule that commands prayer at fixed hours regardless of the disposition of the one praying.",
          pt_step="Reze hoje na hora marcada, mesmo que dure dois minutos.",
          en_step="Pray at the set hour today, even if it lasts two minutes."),

        r("clara-assis", (142, (7,)), (142, (7,)),
          "O pedido é de presteza porque o espírito desfalece: o salmo admite que há um limite e o diz.",
          "The request is for speed because the spirit faints away: the psalm admits there is a limit and says so.",
          pt_title="Atende-me com presteza", en_title="Hear me speedily",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Passou décadas acamada e continuou a rezar o ofício com as irmãs a partir da própria cama.",
          en_why="She spent decades bedridden and went on praying the office with her sisters from her own bed.",
          pt_step="Peça ajuda hoje a alguém para rezar com você.",
          en_step="Ask someone today to pray with you."),

        r("agostinho", (37, (11,)), (37, (11,)),
          "O salmo diz que a força abandona e que a luz dos olhos se vai: descreve a aridez como perda de recursos, não de fé.",
          "The psalm says his strength has left him and the light of his eyes is gone: it describes dryness as loss of resources, not of faith.",
          pt_title="A força me abandona", en_title="My strength has left me",
          pt_saint="Santo Agostinho", en_saint="Saint Augustine",
          pt_why="Escreveu que o coração está inquieto até repousar em Deus, e descreveu essa inquietação como longa.",
          en_why="He wrote that the heart is restless until it rests in God, and described that restlessness as long.",
          pt_step="Escreva hoje uma frase sobre o que você não está conseguindo.",
          en_step="Write one sentence today about what you are not managing."),

        r("oscar-romero", (60, (3,)), (60, (3,)),
          "O clamor vem dos confins da terra com o coração desfalecendo: o salmo permite rezar de muito longe.",
          "The cry comes from the ends of the earth as the heart faints: the psalm allows praying from very far off.",
          pt_title="Dos confins", en_title="From the ends of the earth",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Fez retiro sozinho antes de assumir posições que o isolariam, e registrou a dúvida nesses cadernos.",
          en_why="He made retreat alone before taking positions that would isolate him, and recorded the doubt in those notebooks.",
          pt_step="Reze hoje de um lugar onde você nunca rezou.",
          en_step="Pray today from a place you have never prayed."),

        r("vicente-paulo", (68, (4,)), (68, (4,)),
          "O salmista está cansado de gritar e a garganta enrouqueceu: a aridez, aqui, é fadiga de pedir.",
          "The psalmist is worn out with crying and his jaws are hoarse: the dryness here is the fatigue of asking.",
          pt_title="Cansado de pedir", en_title="Worn out with crying",
          pt_saint="São Vicente de Paulo", en_saint="Saint Vincent de Paul",
          pt_why="Organizou obras que levaram décadas para funcionar, e escreveu sobre a lentidão delas sem as abandonar.",
          en_why="He organized works that took decades to function, and wrote about their slowness without abandoning them.",
          pt_step="Pare hoje de pedir e passe o tempo da oração calado.",
          en_step="Stop asking today and spend your prayer time silent."),
    ],
}
