# -*- coding: utf-8 -*-
"""Bloco 5 — desolação: guilty e lonely.

`guilty` dispara a tela de encaminhamento pastoral e o desvio de escrúpulo.
Regras que valem para as quinze respostas deste estado, e que eu segui:

- Nenhum passo promete alívio nem diz que a culpa vai passar.
- Nenhum passo substitui a confissão; vários apontam para ela com data.
- Nenhuma linguagem clínica ou de diagnóstico.
- Nenhum passo convida a reexaminar a mesma dúvida de consciência — o que
  alimenta o escrúpulo em vez de aliviá-lo. Quando o passo trata disso, ele
  manda parar e levar a um confessor fixo.
"""

from exam_relief_content._shared import r

BLOCK = {
    "guilty": [
        r("agostinho", (50, (3,)), (50, (3,)),
          "O Miserere mede o pedido pela misericórdia de Deus, não pelo tamanho da culpa de quem pede.",
          "The Miserere measures the request by God's mercy, not by the size of the sin of the one asking.",
          pt_title="Segundo a tua misericórdia", en_title="According to your mercy",
          pt_saint="Santo Agostinho", en_saint="Saint Augustine",
          pt_why="Contou por extenso os próprios desvios nas Confissões, escritas quando já era bispo de Hipona.",
          en_why="He recounted his own wanderings at length in the Confessions, written when he was already bishop of Hippo.",
          pt_step="Marque hoje no calendário a data e o horário da sua próxima confissão.",
          en_step="Put the date and time of your next confession in your calendar today."),

        r("padre-pio", (31, (5,)), (31, (5,)),
          "O salmo põe o dizer antes do perdão: confessei, não ocultei. O que ele pede é o ato de nomear, uma vez.",
          "The psalm puts the saying before the pardon: I acknowledged, I did not hide. What it asks is the act of naming, once.",
          pt_title="Não ocultei", en_title="I did not hide it",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Atendeu confissões por décadas em San Giovanni Rotondo e era conhecido por ser breve e direto no confessionário.",
          en_why="He heard confessions for decades at San Giovanni Rotondo and was known for being brief and direct in the confessional.",
          pt_step="Escreva numa linha só o que você vai levar à confissão, e guarde o papel.",
          en_step="Write in a single line what you will take to confession, and keep the paper."),

        r("joao-batista", (129, (3,)), (129, (3,)),
          "A pergunta do salmo — quem subsistiria — não é acusação: é a razão pela qual Deus não guarda registro.",
          "The psalm's question — who shall stand it — is not an accusation: it is the reason God keeps no record.",
          pt_title="Quem subsistiria", en_title="Who could stand",
          pt_saint="São João Batista", en_saint="Saint John the Baptist",
          pt_why="Pregou a conversão como começo, não como condenação, e apontava para outro que vinha depois dele.",
          en_why="He preached conversion as a beginning, not a condemnation, and pointed to another coming after him.",
          pt_step="Pare hoje de reler a mesma falta pela segunda vez no dia.",
          en_step="Stop rereading the same fault a second time today."),

        r("pedro-paulo", (24, (11,)), (24, (11,)),
          "O perdão é pedido por causa do nome de Deus: o salmo não o funda em nada que o pecador possa apresentar.",
          "Pardon is asked for the sake of God's name: the psalm does not found it on anything the sinner can present.",
          pt_title="Por causa do teu nome", en_title="For your name's sake",
          pt_saint="São Pedro", en_saint="Saint Peter",
          pt_why="Negou Jesus três vezes e recebeu depois, à beira do lago, três perguntas sobre amor e o encargo de apascentar.",
          en_why="He denied Jesus three times and afterwards received, by the lake, three questions about love and the charge to feed the flock.",
          pt_step="Retome hoje uma tarefa que você abandonou por se achar indigno dela.",
          en_step="Take up again today a task you abandoned out of feeling unworthy of it."),

        r("maria-madalena", (102, (10,)), (102, (10,)),
          "O salmo afirma que Deus não nos trata segundo os pecados: a medida do trato dele é outra, e é ele quem a escolhe.",
          "The psalm states God has not dealt with us according to our sins: his measure is another, and it is his to choose.",
          pt_title="Não nos trata assim", en_title="He has not dealt so with us",
          pt_saint="Santa Maria Madalena", en_saint="Saint Mary Magdalene",
          pt_why="Os Evangelhos a apresentam entre os que seguiam Jesus depois de curada, e como a primeira enviada a anunciar a Ressurreição.",
          en_why="The Gospels place her among those who followed Jesus after being healed, and as the first sent to announce the Resurrection.",
          pt_step="Faça hoje uma coisa boa que você acha que não tem direito de fazer.",
          en_step="Do one good thing today that you feel you have no right to do."),

        r("inacio-loyola", (50, (19,)), (50, (19,)),
          "O que o salmo chama de sacrifício é o espírito contrito, e ele diz que Deus não o despreza. É recebido, não avaliado.",
          "What the psalm calls sacrifice is an afflicted spirit, and it says God does not despise it. It is received, not assessed.",
          pt_title="Um espírito contrito", en_title="A contrite spirit",
          pt_saint="Santo Inácio de Loyola", en_saint="Saint Ignatius of Loyola",
          pt_why="Escreveu nos Exercícios regras para reconhecer a falsa tristeza, depois de anos sofrendo com escrúpulos em Manresa.",
          en_why="He wrote rules in the Exercises for recognizing false sadness, after years of suffering from scruples at Manresa.",
          pt_step="Se a mesma dúvida voltar hoje, não a reexamine: escreva a data e leve ao confessor.",
          en_step="If the same doubt returns today, do not re-examine it: write the date and take it to a confessor."),

        r("monica", (78, (8,)), (78, (8,)),
          "O pedido é para que as culpas antigas não sejam recordadas contra quem pede: o salmo trata o passado como encerrável.",
          "The request is that former iniquities not be remembered against the one asking: the psalm treats the past as closable.",
          pt_title="Não recordes contra nós", en_title="Remember not against us",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Foi corrigida na juventude por uma serva, segundo as Confissões, e é lembrada pelo que fez depois, não pelo hábito antigo.",
          en_why="She was corrected in youth by a servant, according to the Confessions, and is remembered for what came after, not for the old habit.",
          pt_step="Pare hoje de contar a alguém uma falta sua já confessada.",
          en_step="Stop telling anyone today about a fault of yours that is already confessed."),

        r("josefina-bakhita", (84, (3,)), (84, (3,)),
          "O salmo diz que a culpa foi perdoada e os pecados cobertos: os dois verbos estão no passado.",
          "The psalm says the iniquity has been forgiven and the sins covered: both verbs are in the past.",
          pt_title="Cobriste os pecados", en_title="You have covered their sins",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Pediu o batismo aos vinte e um anos e recebeu os três sacramentos da iniciação no mesmo dia, em 1890.",
          en_why="She asked for baptism at twenty-one and received the three sacraments of initiation on the same day, in 1890.",
          pt_step="Faça hoje um sinal da cruz com água benta ao sair de casa.",
          en_step="Make the sign of the cross with holy water today as you leave home."),

        r("rita-cassia", (37, (5,)), (37, (5,)),
          "O peso é descrito como maior que a cabeça de quem o carrega: o salmo não minimiza, e mesmo assim continua falando com Deus.",
          "The burden is described as heavier than the head of the one carrying it: the psalm does not minimize, and still keeps speaking to God.",
          pt_title="Mais alto que a minha cabeça", en_title="Gone over my head",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Trabalhou para impedir que os filhos vingassem o assassinato do pai, e depois os perdeu por doença.",
          en_why="She worked to keep her sons from avenging their father's murder, and afterwards lost them to illness.",
          pt_step="Peça hoje desculpa a uma pessoa, sem justificar o que você fez.",
          en_step="Apologize to one person today, without justifying what you did."),

        r("vicente-paulo", (118, (176,)), (118, (176,)),
          "O salmista se diz ovelha desgarrada e pede que o pastor o busque: a iniciativa do retorno é pedida a Deus.",
          "The psalmist calls himself a lost sheep and asks the shepherd to seek him: the initiative of return is asked of God.",
          pt_title="Busca o teu servo", en_title="Seek your servant",
          pt_saint="São Vicente de Paulo", en_saint="Saint Vincent de Paul",
          pt_why="Organizou missões populares na França para chegar a quem estava longe da prática, indo aos lugares em vez de esperar.",
          en_why="He organized popular missions across France to reach those far from practice, going to the places instead of waiting.",
          pt_step="Volte hoje a uma igreja onde você não entra há tempo.",
          en_step="Walk today into a church you have not entered in a long time."),

        r("oscar-romero", (68, (6,)), (68, (6,)),
          "O salmista diz que Deus conhece a sua insipiência: o salmo supõe que Deus já sabe antes de ouvir.",
          "The psalmist says God knows his foolishness: the psalm assumes God already knows before hearing.",
          pt_title="Tu conheces", en_title="You know",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Reconheceu publicamente ter mudado de posição sobre a situação do país depois de 1977, sem esconder o antes.",
          en_why="He publicly acknowledged having changed his position on the country's situation after 1977, without hiding what came before.",
          pt_step="Reconheça hoje em voz alta, a uma pessoa, que você estava errado em algo.",
          en_step="Admit out loud to one person today that you were wrong about something."),

        r("jose", (31, (1,)), (31, (1,)),
          "O bem-aventurado do salmo é o perdoado, não o irrepreensível: a bem-aventurança está do lado de quem recebeu.",
          "The blessed one in the psalm is the forgiven, not the blameless: the beatitude sits with the one who received.",
          pt_title="Bem-aventurado o perdoado", en_title="Blessed is the forgiven",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Decidiu não expor Maria publicamente quando podia fazê-lo, segundo o Evangelho de Mateus.",
          en_why="He decided not to expose Mary publicly when he could have, according to Matthew's Gospel.",
          pt_step="Deixe hoje de comentar a falta de outra pessoa.",
          en_step="Refrain today from commenting on another person's fault."),

        r("teresinha", (39, (13,)), (39, (13,)),
          "Os males são ditos sem conta, e o salmista continua a pedir socorro: a quantidade não é motivo para parar de pedir.",
          "The evils are called without number, and the psalmist goes on asking for help: the amount is no reason to stop asking.",
          pt_title="Sem conta", en_title="Without number",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Comparou-se a uma criança que não consegue subir a escada e conta com ser carregada, em vez de medir o próprio progresso.",
          en_why="She compared herself to a child who cannot climb the stairs and counts on being carried, instead of measuring her own progress.",
          pt_step="Reze hoje um ato de contrição e não repita nenhuma outra oração de culpa.",
          en_step="Pray one act of contrition today and repeat no other prayer of guilt."),

        r("edith-stein", (106, (17,)), (106, (17,)),
          "O salmo conta que Deus os tirou do caminho da própria iniquidade: quem age primeiro é ele.",
          "The psalm recounts that God took them out of the way of their iniquity: the one acting first is he.",
          pt_title="Tirou-os do caminho", en_title="He took them out of the way",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Foi atéia por anos na juventude e descreveu depois a leitura da autobiografia de Teresa de Ávila numa única noite.",
          en_why="She was an atheist for years in her youth and later described reading Teresa of Ávila's autobiography in a single night.",
          pt_step="Leia hoje dez páginas de um livro que fale de conversão.",
          en_step="Read ten pages today of a book about conversion."),

        r("filipe-neri", (55, (2,)), (55, (2,)),
          "O salmista pede piedade sem antes provar arrependimento suficiente: o pedido vem primeiro, na primeira linha.",
          "The psalmist asks for mercy without first proving enough repentance: the request comes first, in the opening line.",
          pt_title="Tem piedade de mim", en_title="Have mercy on me",
          pt_saint="São Filipe Néri", en_saint="Saint Philip Neri",
          pt_why="Dizia a penitentes escrupulosos coisas deliberadamente leves, para desarmar a insistência sobre a própria culpa.",
          en_why="He said deliberately light things to scrupulous penitents, to disarm their insistence on their own guilt.",
          pt_step="Faça hoje uma coisa agradável e lícita sem sentir que precisa merecer.",
          en_step="Do one pleasant and lawful thing today without feeling you must earn it."),
    ],

    "lonely": [
        r("andre-bessette", (67, (7,)), (67, (7,)),
          "Deus é apresentado preparando casa para os desamparados: a solidão do salmo tem resposta em forma de moradia.",
          "God is shown making a home for the forsaken: the psalm's loneliness is answered with a dwelling.",
          pt_title="Casa para quem não tem", en_title="A home for the forsaken",
          pt_saint="Santo André Bessette", en_saint="Saint André Bessette",
          pt_why="Recebeu sozinho, na portaria de um colégio em Montreal, milhares de visitantes ao longo de quarenta anos.",
          en_why="Alone at a college door in Montreal, he received thousands of visitors over forty years.",
          pt_step="Bata hoje na porta de um vizinho, sem motivo.",
          en_step="Knock on a neighbour's door today, for no reason."),

        r("teresinha", (24, (16,)), (24, (16,)),
          "O salmista pede que Deus olhe justamente porque está só: a solidão é apresentada como razão do pedido, não como obstáculo.",
          "The psalmist asks God to look precisely because he is alone: loneliness is the reason for the request, not an obstacle to it.",
          pt_title="Só e aflito", en_title="Alone and poor",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Entrou no Carmelo aos quinze anos e escreveu sobre a solidão interior dos últimos meses sem contá-la às irmãs.",
          en_why="She entered Carmel at fifteen and wrote about the inner solitude of her last months without telling her sisters.",
          pt_step="Diga hoje a uma pessoa que você está se sentindo sozinho.",
          en_step="Tell one person today that you are feeling alone."),

        r("joao-cruz", (101, (8,)), (101, (8,)),
          "A imagem é de um pássaro solitário no telhado, acordado: o salmo descreve a solidão como vigília, não como abandono.",
          "The image is a sparrow alone on the housetop, awake: the psalm describes loneliness as a watch, not as abandonment.",
          pt_title="Um pássaro no telhado", en_title="A sparrow on the housetop",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Escreveu o Cântico Espiritual no cárcere de Toledo, numa cela sem janela, guardando os versos de memória.",
          en_why="He composed the Spiritual Canticle in the Toledo prison, in a cell without a window, keeping the verses by memory.",
          pt_step="Escreva hoje quatro linhas sobre como você está, para ninguém.",
          en_step="Write four lines today about how you are, for no one."),

        r("rita-cassia", (87, (9,)), (87, (9,)),
          "O salmo diz que os conhecidos foram afastados, e atribui isso a Deus: não esconde a dureza da frase.",
          "The psalm says acquaintances have been put far away, and lays it to God: it does not soften the hardness of the line.",
          pt_title="Afastaste os meus conhecidos", en_title="You put my friends far from me",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Passou os últimos quinze anos em reclusão no mosteiro por causa de uma ferida que não sarava.",
          en_why="She spent her last fifteen years in seclusion in the monastery because of a wound that would not heal.",
          pt_step="Reze hoje por quem se afastou de você, pelo nome.",
          en_step="Pray today by name for someone who drew away from you."),

        r("jose-sanchez-del-rio", (141, (5,)), (141, (5,)),
          "O salmista olha para o lado e vê que não há ninguém: o salmo registra a constatação sem consertá-la na mesma frase.",
          "The psalmist looks to his right and sees no one: the psalm records the finding without repairing it in the same line.",
          pt_title="Não há quem se importe", en_title="There was no one",
          pt_saint="São José Sánchez del Río", en_saint="Saint José Sánchez del Río",
          pt_why="Foi preso aos catorze anos e mantido numa igreja transformada em cárcere antes de morrer, em 1928.",
          en_why="He was taken at fourteen and held in a church turned into a prison before dying, in 1928.",
          pt_step="Visite hoje alguém que está preso em casa por doença ou idade.",
          en_step="Visit today someone shut in at home by illness or age."),

        r("monica", (26, (10,)), (26, (10,)),
          "O salmo imagina o abandono pelos próprios pais e responde com o acolhimento de Deus: a frase não nega a primeira parte.",
          "The psalm imagines abandonment by one's own parents and answers with God's welcome: the line does not deny the first half.",
          pt_title="Ainda que me abandonem", en_title="Though they leave me",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Seguiu o filho por três países e morreu em Óstia, longe da própria terra, poucos meses depois da conversão dele.",
          en_why="She followed her son through three countries and died at Ostia, far from her own land, months after his conversion.",
          pt_step="Ligue hoje para um parente com quem você não fala há meses.",
          en_step="Call a relative today you have not spoken to in months."),

        r("francisco-xavier", (68, (9,)), (68, (9,)),
          "O salmista se diz estranho para os próprios irmãos: a solidão descrita é entre os seus, não longe deles.",
          "The psalmist calls himself a stranger to his own brethren: the loneliness described is among his own, not far from them.",
          pt_title="Estranho entre os meus", en_title="A stranger to my brethren",
          pt_saint="São Francisco Xavier", en_saint="Saint Francis Xavier",
          pt_why="Passou dez anos em terras onde não falava a língua e escrevia cartas que levavam mais de um ano para chegar.",
          en_why="He spent ten years in lands whose language he did not speak, writing letters that took over a year to arrive.",
          pt_step="Aprenda hoje a dizer uma coisa no idioma de alguém perto de você.",
          en_step="Learn to say one thing today in the language of someone near you."),

        r("edith-stein", (118, (19,)), (118, (19,)),
          "O salmista se diz peregrino na terra e, por isso mesmo, pede os mandamentos: a solidão pede instrução, não companhia.",
          "The psalmist calls himself a sojourner and therefore asks for the commandments: the loneliness asks for instruction, not company.",
          pt_title="Peregrino na terra", en_title="A sojourner on the earth",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Mudou de país duas vezes fugindo da perseguição e escreveu até os últimos dias no Carmelo de Echt.",
          en_why="She moved country twice fleeing persecution and kept writing to her last days in the Carmel of Echt.",
          pt_step="Leia hoje um trecho do Evangelho em vez de procurar conversa.",
          en_step="Read a passage of the Gospel today instead of looking for conversation."),

        r("damiao-molokai", (30, (12,)), (30, (12,)),
          "O salmista se diz objeto de opróbrio para quem o cerca: a solidão do salmo inclui a vergonha de ser visto assim.",
          "The psalmist calls himself a reproach to those around him: the psalm's loneliness includes the shame of being seen so.",
          pt_title="Objeto de opróbrio", en_title="A reproach",
          pt_saint="São Damião de Molokai", en_saint="Saint Damien of Molokai",
          pt_why="Escreveu aos superiores usando \"nós, leprosos\" depois de contrair a doença, e não pediu para sair da ilha.",
          en_why="He wrote to his superiors using \"we lepers\" after contracting the disease, and did not ask to leave the island.",
          pt_step="Sente-se hoje ao lado de quem ninguém senta.",
          en_step="Sit today beside the person nobody sits beside."),

        r("clara-assis", (24, (15,)), (24, (15,)),
          "Os olhos voltados para o Senhor são dados como o que se faz na solidão: uma direção do olhar, não um estado de alma.",
          "Eyes ever towards the Lord are given as what one does in loneliness: a direction of looking, not a state of soul.",
          pt_title="Os olhos voltados", en_title="Eyes ever towards",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Ficou em São Damião mais de quarenta anos, os últimos vinte e sete deles acamada.",
          en_why="She stayed at San Damiano for over forty years, the last twenty-seven of them bedridden.",
          pt_step="Fique hoje cinco minutos olhando um crucifixo, sem dizer nada.",
          en_step="Spend five minutes today looking at a crucifix, saying nothing."),

        r("maria-madalena", (55, (9,)), (55, (9,)),
          "As lágrimas são recolhidas e os caminhos anotados: o salmo diz que a solidão foi registrada por alguém.",
          "The tears are gathered and the wanderings written down: the psalm says the loneliness was recorded by someone.",
          pt_title="Recolhidas as lágrimas", en_title="My tears in your sight",
          pt_saint="Santa Maria Madalena", en_saint="Saint Mary Magdalene",
          pt_why="Ficou junto ao sepulcro depois que os outros discípulos foram embora, segundo o Evangelho de João.",
          en_why="She stayed at the tomb after the other disciples had gone, according to John's Gospel.",
          pt_step="Fique hoje num lugar difícil por cinco minutos a mais.",
          en_step="Stay in one hard place today for five minutes longer."),

        r("carlo-acutis", (41, (7,)), (41, (7,)),
          "O salmista fala consigo mesmo sobre a própria alma deprimida: a solidão aqui é conversa interna admitida.",
          "The psalmist speaks to himself about his own troubled soul: the loneliness here is inner conversation admitted.",
          pt_title="Dentro de mim mesmo", en_title="Within myself",
          pt_saint="São Carlo Acutis", en_saint="Saint Carlo Acutis",
          pt_why="Era adolescente numa escola comum e mantinha sozinho a rotina de Missa diária que os colegas não partilhavam.",
          en_why="He was a teenager in an ordinary school and kept alone the daily Mass routine his classmates did not share.",
          pt_step="Faça hoje a sua prática de fé mesmo sem ninguém acompanhando.",
          en_step="Keep your practice of faith today even with nobody joining."),

        r("oscar-romero", (21, (12,)), (21, (12,)),
          "O pedido é para que Deus não esteja longe, dito com a tribulação já próxima: o salmo pede presença, não resolução.",
          "The request is that God not depart, said with tribulation already near: the psalm asks for presence, not resolution.",
          pt_title="Não estejas longe", en_title="Depart not from me",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Ficou isolado por parte do próprio episcopado depois de suas homilias, e continuou a pregá-las.",
          en_why="He was isolated by part of his own episcopate after his homilies, and went on preaching them.",
          pt_step="Vá hoje à Missa mesmo indo sozinho.",
          en_step="Go to Mass today even going alone."),

        r("josefina-bakhita", (87, (19,)), (87, (19,)),
          "O verso termina dizendo que os familiares são as trevas: o salmo não oferece consolo na mesma frase, e ainda assim é oração.",
          "The verse ends saying that darkness is his acquaintance: the psalm offers no comfort in the same line, and is still prayer.",
          pt_title="Os meus familiares são as trevas", en_title="Darkness is my acquaintance",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Foi separada da família aos sete anos e nunca soube o próprio nome de nascimento nem voltou a encontrá-los.",
          en_why="She was taken from her family at seven, never knew her own birth name, and never found them again.",
          pt_step="Reze hoje por alguém que você nunca vai reencontrar.",
          en_step="Pray today for someone you will never meet again."),

        r("benito", (61, (3,)), (61, (3,)),
          "O salmo chama Deus de rochedo e baluarte no singular — \"só ele\" — e é isso que responde ao estar só.",
          "The psalm calls God rock and protector in the singular — \"he alone\" — and that is what answers being alone.",
          pt_title="Só ele", en_title="He alone",
          pt_saint="São Bento", en_saint="Saint Benedict",
          pt_why="Viveu três anos numa gruta em Subiaco antes de reunir discípulos, e escreveu depois uma regra sobre viver em comum.",
          en_why="He lived three years in a cave at Subiaco before gathering disciples, and afterwards wrote a rule about living in common.",
          pt_step="Passe hoje meia hora sozinho de propósito, sem tela.",
          en_step="Spend half an hour alone on purpose today, with no screen."),
    ],
}
