# -*- coding: utf-8 -*-
"""Bloco 2 — consolação: joyful e hopeful."""

from exam_relief_content._shared import r

BLOCK = {
    "joyful": [
        r("francisco-assis", (117, (24,)), (117, (24,)),
          "O salmo não manda produzir alegria: aponta um dia já feito e convida a se alegrar nele.",
          "The psalm does not command you to produce joy: it points to a day already made and invites you into it.",
          pt_title="Este é o dia", en_title="This is the day",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Compôs o Cântico das Criaturas louvando sol, água e fogo já doente e quase cego.",
          en_why="He composed the Canticle of the Creatures praising sun, water and fire while already ill and nearly blind.",
          pt_step="Saia por cinco minutos e olhe uma coisa viva com atenção.",
          en_step="Step outside for five minutes and look at one living thing attentively."),

        r("filipe-neri", (125, (2,)), (125, (2,)),
          "A boca cheia de riso aparece como consequência de uma libertação, não como distração dela.",
          "The mouth filled with laughter appears as the consequence of a deliverance, not as a distraction from it.",
          pt_title="A boca cheia de riso", en_title="Our mouth filled with laughter",
          pt_saint="São Filipe Néri", en_saint="Saint Philip Neri",
          pt_why="Tratava o bom humor como parte da formação, e chegou a mandar penitentes fazerem coisas ridículas para curar a vaidade.",
          en_why="He treated good humour as part of formation, and would set penitents ridiculous tasks to cure vanity.",
          pt_step="Conte hoje uma coisa engraçada para alguém, sem ironia.",
          en_step="Tell someone something funny today, without irony."),

        r("joao-bosco", (46, (2,)), (46, (2,)),
          "O salmo manda bater palmas: a alegria é dada como gesto do corpo, não como estado interior.",
          "The psalm tells you to clap: joy is given as a gesture of the body, not as an inward state.",
          pt_title="Batei palmas", en_title="Clap your hands",
          pt_saint="São João Bosco", en_saint="Saint John Bosco",
          pt_why="Pôs música, teatro e jogos no centro dos oratórios de Turim, junto da escola e da confissão.",
          en_why="He put music, theatre and games at the centre of the Turin oratories, alongside school and confession.",
          pt_step="Faça hoje uma brincadeira com uma criança, no tempo dela.",
          en_step="Play with a child today, at the child's pace."),

        r("teresinha", (91, (5,)), (91, (5,)),
          "A alegria do salmista vem das obras de Deus, coisas que ele olhou — não de um esforço de ânimo.",
          "The psalmist's delight comes from God's doings, things he looked at — not from an effort of mood.",
          pt_title="Alegre com as tuas obras", en_title="Glad in your doings",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Encontrava no cotidiano do Carmelo de Lisieux a matéria da sua pequena via, sem sair do convento.",
          en_why="She found the matter of her little way in the daily round of the Lisieux Carmel, never leaving the convent.",
          pt_step="Anote uma coisa comum de hoje que deu certo e você não notou.",
          en_step="Write down one ordinary thing from today that went well and you did not notice."),

        r("maria-madalena", (29, (12,)), (29, (12,)),
          "O verbo é converter: o salmo fala de um pranto que foi transformado, não substituído.",
          "The verb is to turn: the psalm speaks of mourning transformed, not replaced.",
          pt_title="Do pranto à dança", en_title="From mourning to dancing",
          pt_saint="Santa Maria Madalena", en_saint="Saint Mary Magdalene",
          pt_why="No Evangelho de João ela chora junto ao sepulcro vazio antes de reconhecer quem a chama pelo nome.",
          en_why="In John's Gospel she weeps at the empty tomb before recognizing the one who calls her by name.",
          pt_step="Reze hoje num lugar onde você já chorou.",
          en_step="Pray today in a place where you once wept."),

        r("carlo-acutis", (32, (1,)), (32, (1,)),
          "A exultação é dirigida aos justos e aos retos: o salmo trata a alegria como coisa que convém a eles.",
          "The rejoicing is addressed to the just and the upright: the psalm treats joy as what becomes them.",
          pt_title="Exultai no Senhor", en_title="Rejoice in the Lord",
          pt_saint="São Carlo Acutis", en_saint="Saint Carlo Acutis",
          pt_why="Usava programação e internet como matéria de vida cristã, e pediu para ser enterrado em Assis.",
          en_why="He used programming and the internet as the matter of a Christian life, and asked to be buried in Assisi.",
          pt_step="Use hoje a sua habilidade mais técnica para ajudar alguém de graça.",
          en_step="Use your most technical skill today to help someone for free."),

        r("clara-assis", (96, (11,)), (96, (11,)),
          "A alegria é descrita como nascendo, como a luz: o salmo a trata como amanhecer, não como decisão.",
          "Joy is described as rising, like light: the psalm treats it as daybreak, not as decision.",
          pt_title="A alegria nasce", en_title="Joy is risen",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Passou mais de quarenta anos em São Damião, boa parte deles acamada, sem sair de Assis.",
          en_why="She spent over forty years at San Damiano, much of it bedridden, without leaving Assisi.",
          pt_step="Abra uma janela ao acordar amanhã, antes de pegar o telefone.",
          en_step="Open a window when you wake tomorrow, before picking up your phone."),

        r("antonio-padua", (63, (11,)), (63, (11,)),
          "O justo se alegra e se refugia no mesmo movimento: o salmo não separa a alegria da proteção.",
          "The just man rejoices and takes refuge in one motion: the psalm does not separate joy from shelter.",
          pt_title="Alegrar-se e refugiar-se", en_title="Rejoice and take refuge",
          pt_saint="Santo Antônio de Pádua", en_saint="Saint Anthony of Padua",
          pt_why="Pregou na Itália e no sul da França e é lembrado pelo conhecimento das Escrituras que sustentava a pregação.",
          en_why="He preached in Italy and southern France and is remembered for the knowledge of Scripture behind his preaching.",
          pt_step="Leia hoje um salmo inteiro em voz alta, um só.",
          en_step="Read one whole psalm out loud today, just one."),

        r("damiao-molokai", (88, (16,)), (88, (16,)),
          "O salmo chama bem-aventurado quem sabe alegrar-se — como se fosse algo que se aprende.",
          "The psalm calls blessed the people that knows jubilation — as if it were something learned.",
          pt_title="Saber alegrar-se", en_title="Knowing how to rejoice",
          pt_saint="São Damião de Molokai", en_saint="Saint Damien of Molokai",
          pt_why="Organizou coral, banda e festas na colônia de Molokai, além dos cuidados com os doentes.",
          en_why="He organized a choir, a band and feast days in the Molokai colony, alongside caring for the sick.",
          pt_step="Cante alguma coisa hoje mesmo sem ter voz boa.",
          en_step="Sing something today even if your voice is poor."),

        r("inacio-loyola", (32, (21,)), (32, (21,)),
          "O coração se alegra porque confia no nome: no salmo, a alegria vem depois da confiança, não antes.",
          "The heart rejoices because it trusts the name: in the psalm, joy follows trust rather than preceding it.",
          pt_title="Nele se alegra o coração", en_title="In him our heart rejoices",
          pt_saint="Santo Inácio de Loyola", en_saint="Saint Ignatius of Loyola",
          pt_why="Ensinou a distinguir as moções interiores em vez de segui-las, e escreveu regras para isso nos Exercícios.",
          en_why="He taught discerning inner movements rather than following them, and wrote rules for it in the Exercises.",
          pt_step="Antes de decidir algo hoje, escreva em uma linha o que você está sentindo.",
          en_step="Before deciding anything today, write in one line what you are feeling."),

        r("josefina-bakhita", (67, (4,)), (67, (4,)),
          "Os justos exultam na presença de Deus: o lugar da alegria, no salmo, é diante dele.",
          "The just rejoice before God: in the psalm, the place of joy is in his presence.",
          pt_title="Exultar na presença", en_title="Rejoicing before God",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Escravizada por anos no Sudão e no Egito, obteve a liberdade em Itália e escolheu permanecer como religiosa.",
          en_why="Enslaved for years in Sudan and Egypt, she obtained her freedom in Italy and chose to remain as a religious.",
          pt_step="Passe dez minutos hoje diante do sacrário, sem pedir nada.",
          en_step="Spend ten minutes before the tabernacle today, asking for nothing."),

        r("martinho-tours", (20, (7,)), (20, (7,)),
          "A alegria aparece como algo com que se é inebriado — recebida, não construída.",
          "Joy appears as something one is filled with — received, not built.",
          pt_title="De alegria inebriado", en_title="Filled with gladness",
          pt_saint="São Martinho de Tours", en_saint="Saint Martin of Tours",
          pt_why="Deixou o exército para ser monge e foi feito bispo de Tours por aclamação popular, contra a própria vontade.",
          en_why="He left the army to be a monk and was made bishop of Tours by popular acclaim, against his own will.",
          pt_step="Aceite hoje um elogio sem desviar o assunto.",
          en_step="Accept a compliment today without deflecting it."),

        r("catarina-siena", (149, (5,)), (149, (5,)),
          "\"Alegrem-se em seus leitos\" põe a alegria no lugar mais privado da casa, longe de qualquer plateia.",
          "\"They shall be joyful in their beds\" puts joy in the most private place in the house, away from any audience.",
          pt_title="Alegres em seus leitos", en_title="Joyful in their beds",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Viveu anos de reclusão em casa antes da vida pública de cartas e negociações políticas.",
          en_why="She lived years of seclusion at home before the public life of letters and political negotiation.",
          pt_step="Reze hoje dentro do seu quarto, com a porta fechada.",
          en_step="Pray in your own room today, with the door shut."),

        r("luis-gonzaga", (4, (8,)), (4, (7,)),
          "A alegria do salmo é comparada à da colheita e declarada maior: não é fuga da realidade, é outra medida.",
          "The psalm's gladness is set beside the harvest's and called greater: not an escape from reality, but another measure.",
          pt_title="Maior que a colheita", en_title="Greater than the harvest",
          pt_saint="São Luís Gonzaga", en_saint="Saint Aloysius Gonzaga",
          pt_why="Renunciou ao marquesado da família para entrar na Companhia de Jesus, contra a resistência do pai.",
          en_why="He renounced his family's marquisate to enter the Society of Jesus, against his father's resistance.",
          pt_step="Deixe hoje de comprar uma coisa que você ia comprar sem pensar.",
          en_step="Skip one purchase today that you were about to make without thinking."),

        r("monica", (32, (11,)), (32, (11,)),
          "O desígnio que permanece é o de Deus, não o nosso: é isso que sustenta a alegria de um dia bom.",
          "The counsel that stands is God's, not ours: that is what holds up the joy of a good day.",
          pt_title="O desígnio que permanece", en_title="The counsel that stands",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Insistiu por décadas na conversão do filho, e viu acontecer o que já havia deixado de parecer possível.",
          en_why="She persisted for decades over her son's conversion, and saw happen what had stopped looking possible.",
          pt_step="Escreva hoje um pedido seu de longo prazo e guarde o papel.",
          en_step="Write down one long-term request of yours today and keep the paper."),
    ],

    "hopeful": [
        r("teresinha", (129, (5,)), (129, (5,)),
          "A espera do salmo não é passiva: é a alma esperando numa palavra dada, com objeto definido.",
          "The psalm's waiting is not passive: it is the soul hoping in a word given, with a definite object.",
          pt_title="Na sua palavra", en_title="In his word",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Passou os últimos dezoito meses entre a tuberculose e uma escuridão de fé que descreveu por escrito.",
          en_why="She spent her last eighteen months between tuberculosis and a darkness of faith she described in writing.",
          pt_step="Copie à mão uma frase da Escritura e deixe-a onde você trabalha.",
          en_step="Copy one line of Scripture by hand and leave it where you work."),

        r("joao-paulo-ii", (26, (14,)), (26, (14,)),
          "O salmo manda três coisas juntas: esperar, ser forte, e esperar de novo. A repetição é o conselho.",
          "The psalm commands three things at once: wait, take courage, and wait again. The repetition is the counsel.",
          pt_title="Espera e sê forte", en_title="Wait and take courage",
          pt_saint="São João Paulo II", en_saint="Saint John Paul II",
          pt_why="Perdeu mãe, irmão e pai antes dos 21 anos, e estudou para o sacerdócio num seminário clandestino durante a ocupação.",
          en_why="He lost his mother, brother and father before he was 21, and studied for the priesthood in a clandestine seminary under occupation.",
          pt_step="Adie hoje uma decisão que você ia tomar por impaciência.",
          en_step="Put off one decision today that you were about to make out of impatience."),

        r("jose", (38, (8,)), (38, (8,)),
          "O salmista pergunta o que pode esperar, e responde nomeando a quem — não o quê.",
          "The psalmist asks what he can hope for, and answers by naming whom — not what.",
          pt_title="Que posso esperar", en_title="What is my hope",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Nos Evangelhos ele muda de planos duas vezes por indicação recebida em sonho, sem explicação dada.",
          en_why="In the Gospels he changes his plans twice on instruction given in a dream, with no explanation offered.",
          pt_step="Deixe hoje uma coisa sem resolver e vá dormir.",
          en_step="Leave one thing unresolved today and go to sleep."),

        r("padre-pio", (70, (5,)), (70, (5,)),
          "A esperança é datada desde a juventude: no salmo, ela tem história, não é um humor de agora.",
          "The hope is dated from youth: in the psalm it has a history, not a present mood.",
          pt_title="Desde a juventude", en_title="From my youth",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Passou anos sob restrições impostas pela própria Igreja, proibido de celebrar em público, antes de serem levantadas.",
          en_why="He spent years under restrictions imposed by the Church itself, forbidden to celebrate publicly, before they were lifted.",
          pt_step="Lembre hoje de uma coisa que você esperou e recebeu, e diga a data.",
          en_step="Recall one thing today you waited for and received, and say the date out loud."),

        r("edith-stein", (145, (5,)), (145, (5,)),
          "O salmo chama ditoso quem tem Deus por protetor, e não quem tem o problema resolvido.",
          "The psalm calls blessed the one who has God for helper, not the one whose problem is solved.",
          pt_title="Ditoso quem espera nele", en_title="Blessed is he whose hope",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Filósofa judia convertida e carmelita, foi deportada de um convento na Holanda e morreu em Auschwitz em 1942.",
          en_why="A Jewish philosopher turned Carmelite, she was deported from a convent in the Netherlands and died at Auschwitz in 1942.",
          pt_step="Escreva hoje o nome de alguém cuja espera é mais dura que a sua, e reze por ele.",
          en_step="Write down today the name of someone whose waiting is harder than yours, and pray for them."),

        r("monica", (39, (2,)), (39, (2,)),
          "O verbo se repete — esperei, esperei — e só depois vem o ouvido inclinado. A ordem importa.",
          "The verb repeats — with expectation I have waited — and only then comes the ear inclined. The order matters.",
          pt_title="Esperei, esperei", en_title="With expectation I waited",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Seguiu o filho de Cartago a Roma e a Milão ao longo de anos, até a conversão dele em 386.",
          en_why="She followed her son from Carthage to Rome and Milan over years, until his conversion in 386.",
          pt_step="Reze hoje pela mesma intenção pela qual você rezou ontem, com as mesmas palavras.",
          en_step="Pray today for the same intention as yesterday, in the same words."),

        r("rita-cassia", (32, (22,)), (32, (22,)),
          "A misericórdia é pedida na medida da esperança: o salmo liga uma à outra explicitamente.",
          "Mercy is asked for in the measure of hope: the psalm ties one to the other explicitly.",
          pt_title="Segundo esperamos", en_title="As we have hoped",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Perdeu o marido assassinado e os dois filhos antes de ser recebida no mosteiro agostiniano de Cássia.",
          en_why="She lost her husband to murder and both her sons before being received into the Augustinian monastery at Cascia.",
          pt_step="Peça hoje uma coisa concreta na oração, e só ela.",
          en_step="Ask for one concrete thing in prayer today, and only that."),

        r("joao-cruz", (118, (81,)), (118, (81,)),
          "O salmista diz que a alma desfalece e, no mesmo verso, que espera. As duas coisas cabem juntas.",
          "The psalmist says his soul has fainted and, in the same verse, that he hopes. Both fit together.",
          pt_title="Desfalecer esperando", en_title="Fainting, and hoping",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Escreveu parte de seus poemas no cárcere de Toledo, sem papel, guardando-os de memória.",
          en_why="He composed part of his poems in the Toledo prison, without paper, keeping them by memory.",
          pt_step="Reze hoje mesmo sem sentir nada, pelo tempo que você já tinha marcado.",
          en_step="Pray today even feeling nothing, for the time you had already set."),

        r("francisco-xavier", (36, (9,)), (36, (9,)),
          "A promessa é para quem espera no Senhor, e o salmo a coloca em contraste com quem prospera pelo mal.",
          "The promise is for those who wait upon the Lord, and the psalm sets it against those who prosper by evil.",
          pt_title="Os que esperam", en_title="They that wait",
          pt_saint="São Francisco Xavier", en_saint="Saint Francis Xavier",
          pt_why="Morreu na ilha de Sanchuão à espera de entrar na China, sem ter conseguido o acesso que buscava.",
          en_why="He died on Shangchuan Island waiting to enter China, never obtaining the access he sought.",
          pt_step="Continue hoje um trabalho que você não vai ver terminado.",
          en_step="Carry on today with work you will not see finished."),

        r("tomas-aquino", (72, (28,)), (72, (28,)),
          "\"É bom estar junto de Deus\" é dito como conclusão de um salmo que começou em escândalo e dúvida.",
          "\"It is good for me to adhere to my God\" is said as the conclusion of a psalm that began in scandal and doubt.",
          pt_title="Bom é estar junto", en_title="It is good to adhere",
          pt_saint="São Tomás de Aquino", en_saint="Saint Thomas Aquinas",
          pt_why="Depois de uma experiência na Missa em dezembro de 1273, deixou de escrever a Suma e não a retomou.",
          en_why="After an experience at Mass in December 1273 he stopped writing the Summa and never took it up again.",
          pt_step="Termine hoje a oração em silêncio, sem mais nenhum pedido.",
          en_step="End your prayer today in silence, with no further request."),

        r("oscar-romero", (61, (8,)), (61, (8,)),
          "Deus é chamado rochedo e salvação no mesmo verso: a esperança do salmo é apoio, não previsão.",
          "God is called rock and salvation in the same verse: the psalm's hope is support, not forecast.",
          pt_title="O rochedo", en_title="The rock",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Arcebispo de São Salvador, foi morto a tiros em março de 1980 enquanto celebrava a Missa numa capela de hospital.",
          en_why="Archbishop of San Salvador, he was shot dead in March 1980 while celebrating Mass in a hospital chapel.",
          pt_step="Faça hoje uma coisa certa que pode te custar algo pequeno.",
          en_step="Do one right thing today that may cost you something small."),

        r("catarina-siena", (30, (25,)), (30, (25,)),
          "O salmo se dirige a todos que esperam e manda o coração fortalecer-se: esperança aqui é ordem coletiva.",
          "The psalm addresses all who hope and tells the heart to be strengthened: hope here is a command to a group.",
          pt_title="Fortaleça-se o coração", en_title="Let your heart be strengthened",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Escreveu ao papa e a governantes em pleno cisma, insistindo no retorno a Roma, sem nenhum cargo.",
          en_why="She wrote to popes and rulers in the middle of schism, insisting on the return to Rome, holding no office.",
          pt_step="Diga hoje a alguém que está desanimado uma coisa verdadeira e concreta.",
          en_step="Say one true, concrete thing today to someone who is discouraged."),

        r("maximiliano-kolbe", (61, (6,)), (61, (6,)),
          "A alma é mandada repousar porque dele vem o que se espera: a paciência tem fonte nomeada.",
          "The soul is told to rest because from him comes what it awaits: the patience has a named source.",
          pt_title="Dele vem o que espero", en_title="From him is my patience",
          pt_saint="São Maximiliano Maria Kolbe", en_saint="Saint Maximilian Kolbe",
          pt_why="Franciscano polonês, ofereceu-se em Auschwitz para morrer no lugar de um pai de família e foi aceito.",
          en_why="A Polish Franciscan, at Auschwitz he offered to die in place of a family man, and was accepted.",
          pt_step="Ofereça hoje um incômodo seu por uma pessoa determinada.",
          en_step="Offer up one inconvenience of yours today for one particular person."),

        r("andre-bessette", (24, (3,)), (24, (3,)),
          "O salmo diz que os que esperam não serão confundidos — uma promessa sobre a vergonha, não sobre o prazo.",
          "The psalm says those who wait shall not be confounded — a promise about shame, not about timing.",
          pt_title="Não serão confundidos", en_title="They shall not be confounded",
          pt_saint="Santo André Bessette", en_saint="Saint André Bessette",
          pt_why="Analfabeto na juventude e de saúde frágil, foi aceito na congregação por intervenção do bispo e serviu como porteiro.",
          en_why="Illiterate in youth and of frail health, he was accepted into his congregation by the bishop's intervention and served as porter.",
          pt_step="Peça hoje uma ajuda que você tem vergonha de pedir.",
          en_step="Ask today for one kind of help you are ashamed to ask for."),

        r("isabel-trindade", (129, (7,)), (129, (7,)),
          "A razão dada é a abundância da redenção: o salmo funda a esperança no que já existe em Deus.",
          "The reason given is plentiful redemption: the psalm founds hope on what already exists in God.",
          pt_title="Copiosa redenção", en_title="Plentiful redemption",
          pt_saint="Santa Isabel da Trindade", en_saint="Saint Elizabeth of the Trinity",
          pt_why="Escreveu sobre a Trindade habitando a alma, e passou os últimos meses de vida com dores por doença de Addison.",
          en_why="She wrote about the Trinity dwelling in the soul, and spent her last months in pain from Addison's disease.",
          pt_step="Repita hoje três vezes, em momentos diferentes, uma frase curta de oração.",
          en_step="Repeat one short line of prayer three times today, at different moments."),
    ],
}
