# -*- coding: utf-8 -*-
"""Bloco 8 — desolação: doubtful e tired.

Salmo 126 divide-se de outro modo nas duas edições: o "em vão vos levantais
antes de amanhecer" está em 126,2 no Matos Soares, e a mesma referência em
Douay traz a vigília inútil de quem guarda a cidade. As duas falam de esforço
sem fruto, e cada idioma tem a sua explicação escrita sobre o seu próprio texto.
"""

from exam_relief_content._shared import r

BLOCK = {
    "doubtful": [
        r("tomas-aquino", (72, (2,)), (72, (2,)),
          "O salmista admite que os pés quase vacilaram: a dúvida é registrada no Saltério como experiência, não como queda.",
          "The psalmist admits his feet were almost moved: doubt is recorded in the Psalter as experience, not as a fall.",
          pt_title="Por pouco não vacilaram", en_title="My feet were almost moved",
          pt_saint="São Tomás de Aquino", en_saint="Saint Thomas Aquinas",
          pt_why="Abria cada questão da Suma pelas objeções, apresentando o argumento contrário antes de responder.",
          en_why="He opened each question of the Summa with the objections, setting out the opposing argument before answering.",
          pt_step="Escreva hoje a sua dúvida na forma mais forte que ela tem.",
          en_step="Write your doubt today in the strongest form it has."),

        r("edith-stein", (76, (8,)), (76, (8,)),
          "A pergunta do salmo é se Deus abandonará para sempre: ela é feita dentro da oração, não contra ela.",
          "The psalm asks whether God will cast off for ever: the question is asked inside prayer, not against it.",
          pt_title="Porventura para sempre", en_title="Will he cast off for ever",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Foi atéia durante anos e escreveu depois que a busca honesta da verdade já era um caminho para Deus.",
          en_why="She was an atheist for years and later wrote that the honest search for truth was already a road to God.",
          pt_step="Leia hoje uma objeção séria à fé, sem procurar a resposta ainda.",
          en_step="Read one serious objection to the faith today, without looking for the answer yet."),

        r("agostinho", (88, (50,)), (88, (50,)),
          "O salmista pergunta onde estão as antigas graças: a dúvida é feita de memória, não de ignorância.",
          "The psalmist asks where the ancient mercies are: the doubt is made of memory, not of ignorance.",
          pt_title="Onde estão as antigas graças", en_title="Where are your ancient mercies",
          pt_saint="Santo Agostinho", en_saint="Saint Augustine",
          pt_why="Passou nove anos entre os maniqueus antes de deixá-los, e descreveu esse período sem apagá-lo.",
          en_why="He spent nine years among the Manicheans before leaving them, and described that period without erasing it.",
          pt_step="Anote hoje uma coisa que você já viu Deus fazer, com data.",
          en_step="Write down today one thing you have seen God do, with a date."),

        r("tomas-aquino", (72, (16,)), (72, (16,)),
          "O salmista diz que refletiu para compreender e achou trabalhoso: a dúvida é apresentada como esforço legítimo.",
          "The psalmist says he studied to know this and found it a labour: doubt is presented as legitimate effort.",
          pt_title="Pareceu-me trabalhoso", en_title="It is a labour",
          pt_saint="São Tomás de Aquino", en_saint="Saint Thomas Aquinas",
          pt_why="Deixou a Suma inacabada e, segundo os relatos, disse que tudo o que escrevera lhe parecia palha.",
          en_why="He left the Summa unfinished and, by the accounts, said all he had written seemed like straw to him.",
          pt_step="Aceite hoje não entender uma coisa, e diga isso em voz alta.",
          en_step="Accept today not understanding one thing, and say so out loud."),

        r("teresinha", (118, (25,)), (118, (25,)),
          "A alma está prostrada sobre o pó e pede vida: o salmo pede que Deus aja primeiro, não que a pessoa se convença.",
          "The soul cleaves to the pavement and asks to be quickened: the psalm asks God to act first, not the person to be convinced.",
          pt_title="Dá-me a vida", en_title="Quicken me",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Escreveu nos últimos meses que já não conseguia crer no céu e que continuava a fazer atos de fé.",
          en_why="In her last months she wrote that she could no longer believe in heaven and that she kept making acts of faith.",
          pt_step="Faça hoje um ato de fé com as palavras da Igreja, sem sentir.",
          en_step="Make an act of faith today in the Church's words, without feeling it."),

        r("pedro-paulo", (105, (24,)), (105, (24,)),
          "O salmo conta que não deram crédito à palavra depois de terem visto: a dúvida é narrada como recaída, e narrada sem condenação.",
          "The psalm recounts that they believed not his word after having seen: the doubt is told as a relapse, and told without condemnation.",
          pt_title="Não deram crédito", en_title="They believed not",
          pt_saint="São Pedro", en_saint="Saint Peter",
          pt_why="Começou a afundar ao andar sobre as águas depois de já ter dado alguns passos, segundo o Evangelho de Mateus.",
          en_why="He began to sink while walking on the water after already taking some steps, according to Matthew's Gospel.",
          pt_step="Peça hoje ajuda a quem já duvidou disso antes de você.",
          en_step="Ask for help today from someone who doubted this before you."),

        r("joao-batista", (41, (10,)), (41, (10,)),
          "O salmista chama Deus de rochedo e no mesmo verso pergunta por que o esquece: crê e duvida na mesma frase.",
          "The psalmist calls God his support and in the same verse asks why he has forgotten him: he believes and doubts in one line.",
          pt_title="Meu rochedo, por que", en_title="My support, why",
          pt_saint="São João Batista", en_saint="Saint John the Baptist",
          pt_why="Mandou perguntar a Jesus, da prisão, se era ele quem havia de vir, depois de já o ter apontado no Jordão.",
          en_why="From prison he sent to ask Jesus whether he was the one to come, after having already pointed him out at the Jordan.",
          pt_step="Faça hoje a sua pergunta a um padre, não à internet.",
          en_step="Put your question today to a priest, not to the internet."),

        r("catarina-siena", (138, (23,)), (138, (23,)),
          "O salmista pede que Deus o sonde e o prove: a dúvida pede exame, e o exame é pedido a Deus.",
          "The psalmist asks God to prove him and know his heart: the doubt asks for examination, and the examining is asked of God.",
          pt_title="Sonda-me", en_title="Prove me",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Submetia as próprias experiências ao julgamento de confessores, e registrou que foi examinada por eles.",
          en_why="She submitted her own experiences to the judgement of confessors, and recorded being examined by them.",
          pt_step="Leve hoje a sua dúvida a alguém que possa te contradizer.",
          en_step="Take your doubt today to someone who can contradict you."),

        r("inacio-loyola", (85, (11,)), (85, (11,)),
          "O pedido é para ser ensinado e depois andar: no salmo, o caminho vem antes da certeza.",
          "The request is to be taught and then to walk: in the psalm, the road comes before the certainty.",
          pt_title="Ensina-me o teu caminho", en_title="Teach me your way",
          pt_saint="Santo Inácio de Loyola", en_saint="Saint Ignatius of Loyola",
          pt_why="Escreveu regras para discernir em tempo de dúvida, e a primeira delas é não mudar decisão tomada em desolação.",
          en_why="He wrote rules for discerning in time of doubt, the first of which is not to change a decision made in desolation.",
          pt_step="Não mude hoje nenhuma decisão que você tomou num dia melhor.",
          en_step="Change no decision today that you made on a better day."),

        r("jose", (24, (5,)), (24, (5,)),
          "O salmista pede direção na verdade: o pedido supõe que a verdade é de Deus, e não do estado de espírito de quem pergunta.",
          "The psalmist asks to be directed in truth: the request assumes truth is God's, not the questioner's state of mind.",
          pt_title="Dirige-me na tua verdade", en_title="Direct me in your truth",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Agiu com base no que recebeu em sonho, sem confirmação exterior, segundo os Evangelhos.",
          en_why="He acted on what he received in a dream, without outward confirmation, according to the Gospels.",
          pt_step="Faça hoje a próxima coisa certa sem esperar ter certeza.",
          en_step="Do the next right thing today without waiting to be sure."),

        r("francisco-xavier", (142, (10,)), (142, (10,)),
          "O pedido é para ser ensinado a fazer a vontade, não a entendê-la: o salmo põe a prática antes da compreensão.",
          "The request is to be taught to do his will, not to understand it: the psalm puts practice before comprehension.",
          pt_title="Ensina-me a fazer", en_title="Teach me to do",
          pt_saint="São Francisco Xavier", en_saint="Saint Francis Xavier",
          pt_why="Foi enviado ao Oriente com poucos dias de aviso, substituindo outro que adoeceu, e partiu sem preparação.",
          en_why="He was sent to the East with a few days' notice, replacing another who fell ill, and left without preparation.",
          pt_step="Faça hoje uma obra de misericórdia concreta, sem resolver a dúvida antes.",
          en_step="Do one concrete work of mercy today, without settling the doubt first."),

        r("padre-pio", (93, (18,)), (93, (18,)),
          "Quando o salmista pensa que o pé vacila, a graça o sustém: a ajuda é descrita chegando dentro da dúvida.",
          "When the psalmist says his foot is moved, mercy assists him: the help is described as arriving inside the doubt.",
          pt_title="Quando penso que vacilo", en_title="If I said my foot is moved",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Foi investigado pela Santa Sé e teve as próprias experiências postas em dúvida oficialmente, e obedeceu.",
          en_why="He was investigated by the Holy See and had his own experiences officially doubted, and obeyed.",
          pt_step="Obedeça hoje a uma prática da Igreja que você não entende bem.",
          en_step="Obey today one practice of the Church you do not fully understand."),

        r("monica", (26, (13,)), (26, (13,)),
          "O salmista diz que espera ver os bens do Senhor na terra dos vivos: a fé aqui é sobre este mundo, e é dita como espera.",
          "The psalmist says he believes he will see the good things of the Lord in the land of the living: the faith here is about this world, and is said as waiting.",
          pt_title="Na terra dos vivos", en_title="In the land of the living",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Disse ao filho que o único motivo para continuar vivendo era vê-lo católico, e viu isso antes de morrer.",
          en_why="She told her son the only reason left to live was to see him a Catholic, and she saw it before she died.",
          pt_step="Diga hoje em voz alta o que você espera ver acontecer.",
          en_step="Say out loud today what you hope to see happen."),

        r("carlo-acutis", (30, (15,)), (30, (15,)),
          "A confiança é declarada com um \"porém eu\": o salmo põe a fé como escolha feita contra o que se conclui.",
          "The trust is declared with a \"but I\": the psalm puts faith as a choice made against what one concludes.",
          pt_title="Porém eu confio", en_title="But I have trusted",
          pt_saint="São Carlo Acutis", en_saint="Saint Carlo Acutis",
          pt_why="Catalogou milagres eucarísticos documentados em vez de defender a fé por argumento abstrato.",
          en_why="He catalogued documented Eucharistic miracles rather than defending the faith by abstract argument.",
          pt_step="Procure hoje um fato verificável sobre uma coisa que você duvida.",
          en_step="Look up one verifiable fact today about something you doubt."),

        r("josefina-bakhita", (12, (2,)), (12, (3,)),
          "O salmo pergunta até quando Deus esconderá o rosto: a pergunta fica, e o salmo continua.",
          "The psalm asks how long his enemy shall be exalted over him: the question stands, and the psalm goes on.",
          pt_title="Até quando esconderás", en_title="How long",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Foi vendida cinco vezes e disse depois que, mesmo sem saber o nome de Deus, o procurava olhando o céu.",
          en_why="She was sold five times and said later that, not knowing God's name, she sought him by looking at the sky.",
          pt_step="Olhe hoje o céu por um minuto, sem formular oração.",
          en_step="Look at the sky for one minute today, forming no prayer."),
    ],

    "tired": [
        r("benito", (126, (2,)), (126, (2,)),
          "O salmo chama de vão o madrugar e o serão: não condena o trabalho, condena a ilusão de que ele sustenta tudo.",
          "The psalm calls the watchman's vigil vain unless the Lord keeps the city: it does not condemn the work, but the illusion that the work holds everything up.",
          pt_title="Em vão vos levantais", en_title="He watches in vain",
          pt_saint="São Bento", en_saint="Saint Benedict",
          pt_why="Dividiu o dia do monge entre oração, trabalho e leitura, com horas fixas para cada um e limite para todos.",
          en_why="He divided the monk's day between prayer, work and reading, with fixed hours for each and a limit on all.",
          pt_step="Pare hoje de trabalhar na hora, mesmo com coisa pendente.",
          en_step="Stop working at the hour today, even with something unfinished."),

        r("teresinha", (102, (14,)), (102, (14,)),
          "O salmo diz que ele sabe de que somos formados e se lembra de que somos pó: o cansaço é previsto, não repreendido.",
          "The psalm says he knows our frame and remembers we are dust: the tiredness is expected, not rebuked.",
          pt_title="Ele sabe do que somos feitos", en_title="He knows our frame",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Escreveu que adormecia na oração e que Deus a recebia assim, como um pai recebe a criança que dorme.",
          en_why="She wrote that she fell asleep at prayer and that God received her so, as a father receives a sleeping child.",
          pt_step="Durma hoje quinze minutos mais, de propósito.",
          en_step="Sleep fifteen minutes longer today, on purpose."),

        r("joao-cruz", (6, (7,)), (6, (7,)),
          "O salmista se diz esgotado de tanto gemer: o salmo dá lugar ao cansaço que vem de sofrer, não de trabalhar.",
          "The psalmist says he has laboured in his groanings: the psalm makes room for the tiredness that comes from suffering, not from working.",
          pt_title="Esgotado de gemer", en_title="Laboured in my groanings",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Saiu do cárcere de Toledo tão debilitado que precisou de meses de recuperação num convento em Almodóvar.",
          en_why="He came out of the Toledo prison so weakened that he needed months of recovery in a house at Almodóvar.",
          pt_step="Não faça hoje a coisa a mais que você ia fazer.",
          en_step="Do not do the extra thing today that you were going to do."),

        r("jose", (22, (2,)), (22, (2,)),
          "O pastor do salmo faz recostar em verdes pastos: o descanso aparece como iniciativa dele, não como recompensa.",
          "The shepherd of the psalm sets him in a place of pasture: the rest appears as his initiative, not as a reward.",
          pt_title="Faz recostar", en_title="He sets me down",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Trabalhou como carpinteiro e é invocado como patrono dos trabalhadores desde o século XX.",
          en_why="He worked as a carpenter and has been invoked as patron of workers since the twentieth century.",
          pt_step="Almoce hoje sem trabalhar ao mesmo tempo.",
          en_step="Eat lunch today without working at the same time."),

        r("clara-assis", (142, (7,)), (142, (7,)),
          "O salmista pede presteza porque o espírito desfalece: ele diz o próprio limite em vez de se forçar.",
          "The psalmist asks for speed because his spirit faints away: he states his own limit instead of pushing past it.",
          pt_title="O meu espírito desfalece", en_title="My spirit faints",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Foi obrigada por Francisco a comer e a dormir mais depois de anos de jejuns que a debilitaram.",
          en_why="Francis obliged her to eat and sleep more after years of fasting that had weakened her.",
          pt_step="Peça hoje a alguém que faça uma tarefa sua.",
          en_step="Ask someone today to take on one of your tasks."),

        r("edith-stein", (118, (28,)), (118, (28,)),
          "O salmo diz que a alma derrama lágrimas de tristeza e pede fortalecimento: o pedido é de força, não de ânimo.",
          "The psalm says his soul has slumbered through heaviness and asks to be strengthened: the request is for strength, not for cheer.",
          pt_title="Fortifica-me", en_title="Strengthen me",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Trabalhou como enfermeira voluntária num hospital de tifo na Primeira Guerra, em turnos longos.",
          en_why="She worked as a volunteer nurse in a typhus hospital in the First World War, on long shifts.",
          pt_step="Beba água e coma alguma coisa antes de rezar hoje.",
          en_step="Drink water and eat something before praying today."),

        r("francisco-assis", (54, (7,)), (54, (7,)),
          "O salmista deseja asas para fugir: o salmo não censura o desejo de escapar, apenas o diz.",
          "The psalmist wishes for wings to fly away: the psalm does not censure the wish to escape, it only says it.",
          pt_title="Asas como a pomba", en_title="Wings like a dove",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Retirou-se para o monte Alverne no fim da vida, depois de deixar o governo da ordem.",
          en_why="He withdrew to Mount La Verna at the end of his life, after leaving the governance of the order.",
          pt_step="Vá hoje a algum lugar sozinho por meia hora.",
          en_step="Go somewhere alone today for half an hour."),

        r("damiao-molokai", (37, (11,)), (37, (11,)),
          "O salmo diz que a força abandona e a luz dos olhos se vai: descreve o esgotamento por partes do corpo.",
          "The psalm says his strength has left him and the light of his eyes is gone: it describes exhaustion part of the body at a time.",
          pt_title="A força me abandona", en_title="My strength has left me",
          pt_saint="São Damião de Molokai", en_saint="Saint Damien of Molokai",
          pt_why="Trabalhou dezesseis anos em Molokai como padre, médico improvisado, carpinteiro e coveiro ao mesmo tempo.",
          en_why="He worked sixteen years at Molokai as priest, improvised doctor, carpenter and gravedigger at once.",
          pt_step="Escolha hoje uma das suas funções e não a exerça.",
          en_step="Pick one of your roles today and do not perform it."),

        r("teresa-avila", (120, (3,)), (120, (3,)),
          "O salmo diz que ele não adormece: a vigília é dele, e isso é dito a quem precisa dormir.",
          "The psalm says he does not slumber: the watching is his, and it is said to someone who needs to sleep.",
          pt_title="Ele não adormece", en_title="He does not slumber",
          pt_saint="Santa Teresa de Ávila", en_saint="Saint Teresa of Ávila",
          pt_why="Escreveu que mandava as noviças comerem e dormirem bem, e que a saúde importava para a oração.",
          en_why="She wrote that she made her novices eat and sleep well, and that health mattered for prayer.",
          pt_step="Vá dormir hoje no horário, sem terminar a lista.",
          en_step="Go to bed on time today, without finishing the list."),

        r("andre-bessette", (60, (4,)), (60, (4,)),
          "Deus é chamado torre sólida: o salmo oferece apoio externo a quem não tem mais força própria.",
          "God is called a tower of strength: the psalm offers outside support to one with no strength left.",
          pt_title="Uma torre sólida", en_title="A tower of strength",
          pt_saint="Santo André Bessette", en_saint="Saint André Bessette",
          pt_why="Viveu com saúde frágil a vida inteira e trabalhou até os noventa anos na portaria e no santuário.",
          en_why="He lived with frail health all his life and worked until he was ninety at the door and at the oratory.",
          pt_step="Apoie-se hoje em alguém, e diga em quê.",
          en_step="Lean on someone today, and say what for."),

        r("rita-cassia", (131, (1,)), (131, (1,)),
          "O salmo pede que Deus se lembre — em favor de outro, não de quem reza: o cansaço não impede intercessão.",
          "The psalm asks God to remember — on another's behalf, not the one praying: tiredness does not prevent intercession.",
          pt_title="Lembra-te, Senhor", en_title="Lord, remember",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Rezou pela conversão do marido durante dezoito anos de casamento difícil, sem deixar a casa.",
          en_why="She prayed for her husband's conversion through eighteen years of a hard marriage, without leaving the house.",
          pt_step="Reze hoje por outra pessoa em vez de por você.",
          en_step="Pray today for someone else instead of for yourself."),

        r("luis-gonzaga", (90, (4,)), (90, (4,)),
          "A imagem é de abrigo sob as penas: o salmo oferece cobertura, não estímulo.",
          "The image is shelter under his wings: the psalm offers covering, not encouragement.",
          pt_title="Debaixo das suas penas", en_title="Under his wings",
          pt_saint="São Luís Gonzaga", en_saint="Saint Aloysius Gonzaga",
          pt_why="Foi mandado descansar pelos superiores por excesso de penitências antes de adoecer no serviço aos doentes.",
          en_why="His superiors ordered him to rest for excessive penances before he fell ill serving the sick.",
          pt_step="Obedeça hoje a alguém que te disse para descansar.",
          en_step="Obey someone today who told you to rest."),

        r("monica", (68, (4,)), (68, (4,)),
          "O salmista está cansado de gritar e enrouqueceu: o salmo admite o cansaço de rezar pela mesma coisa.",
          "The psalmist is worn out with crying and his jaws are hoarse: the psalm admits the tiredness of praying for the same thing.",
          pt_title="Enrouqueceu a garganta", en_title="My jaws are hoarse",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Pediu a mesma coisa por quase trinta anos, e chorou diante de bispos que lhe disseram para esperar.",
          en_why="She asked for the same thing for nearly thirty years, weeping before bishops who told her to wait.",
          pt_step="Reze hoje em silêncio, sem repetir o pedido antigo.",
          en_step="Pray in silence today, without repeating the old request."),

        r("oscar-romero", (142, (7,)), (61, (2,)),
          "O salmo pede socorro pronto porque o espírito não aguenta mais: o pedido tem urgência declarada.",
          "The psalm says the soul rests in God alone, from whom salvation comes: the resting is placed outside the one who is tired.",
          pt_title="Com presteza", en_title="In God alone my soul rests",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Pregava homilias de mais de uma hora todas as semanas enquanto atendia famílias de vítimas, por três anos.",
          en_why="He preached homilies of over an hour every week while receiving victims' families, for three years.",
          pt_step="Reduza hoje uma coisa que você faz por hábito e não por dever.",
          en_step="Cut back today on one thing you do from habit and not from duty."),

        r("josefina-bakhita", (102, (14,)), (4, (9,)),
          "O salmo lembra que somos pó, e é isso que sustenta o pedido de trégua.",
          "The psalm says that in peace he will sleep and rest, because God alone settles him in safety.",
          pt_title="Somos pó", en_title="In peace I will sleep",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Trabalhou como cozinheira e porteira do convento em Schio até os últimos anos, já com dores.",
          en_why="She worked as cook and doorkeeper of the convent at Schio until her last years, already in pain.",
          pt_step="Faça hoje só o trabalho do dia, e não o de amanhã.",
          en_step="Do only today's work today, and not tomorrow's."),
    ],
}
