# -*- coding: utf-8 -*-
"""Bloco 3 — consolação: forgiven e loved."""

from exam_relief_content._shared import r

BLOCK = {
    "forgiven": [
        r("agostinho", (31, (1,)), (31, (1,)),
          "O salmo chama bem-aventurado quem foi perdoado — não quem nunca errou.",
          "The psalm calls blessed the one whose sin is forgiven — not the one who never sinned.",
          pt_title="Bem-aventurado o perdoado", en_title="Blessed is the forgiven",
          pt_saint="Santo Agostinho", en_saint="Saint Augustine",
          pt_why="Escreveu as Confissões já bispo, contando os próprios desvios por extenso e sem atenuação.",
          en_why="He wrote the Confessions as a bishop, recounting his own wanderings at length and without softening.",
          pt_step="Agradeça hoje por um perdão concreto que você já recebeu.",
          en_step="Give thanks today for one concrete pardon you have already received."),

        r("maria-madalena", (102, (12,)), (102, (12,)),
          "A distância é geográfica no salmo: oriente e ocidente. Não é esquecimento, é afastamento.",
          "The distance in the psalm is geographic: east and west. Not forgetting, but removal.",
          pt_title="Quanto o oriente dista", en_title="As far as the east",
          pt_saint="Santa Maria Madalena", en_saint="Saint Mary Magdalene",
          pt_why="Os Evangelhos a apresentam entre os que seguiam Jesus depois de ter sido curada, e junto à cruz até o fim.",
          en_why="The Gospels place her among those who followed Jesus after being healed, and at the cross to the end.",
          pt_step="Pare hoje de reler uma mensagem antiga que só serve para se acusar.",
          en_step="Stop rereading today one old message that only serves to accuse you."),

        r("padre-pio", (50, (12,)), (50, (12,)),
          "O salmista pede que o coração seja criado, não corrigido: o verbo é de obra nova.",
          "The psalmist asks for a heart to be created, not repaired: the verb is of new making.",
          pt_title="Cria em mim", en_title="Create in me",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Passou décadas atendendo confissões em San Giovanni Rotondo, por muitas horas ao dia.",
          en_why="He spent decades hearing confessions at San Giovanni Rotondo, for many hours a day.",
          pt_step="Marque hoje a data da sua próxima confissão, no calendário.",
          en_step="Set the date of your next confession today, in your calendar."),

        r("joao-batista", (129, (3,)), (129, (3,)),
          "A pergunta do salmo é retórica: se Deus guardasse os delitos, ninguém subsistiria. Por isso ele não guarda.",
          "The psalm's question is rhetorical: if God marked iniquities, no one would stand. Which is why he does not.",
          pt_title="Quem subsistiria", en_title="Who shall stand it",
          pt_saint="São João Batista", en_saint="Saint John the Baptist",
          pt_why="Pregou a conversão junto ao Jordão e foi preso e morto por dizer a verdade diante de Herodes.",
          en_why="He preached conversion at the Jordan and was imprisoned and killed for telling the truth before Herod.",
          pt_step="Confesse hoje uma coisa concreta a alguém que você prejudicou.",
          en_step="Admit one concrete thing today to someone you wronged."),

        r("pedro-paulo", (31, (5,)), (31, (5,)),
          "O perdão vem no salmo depois de dizer: não ocultei a culpa. O reconhecimento vem primeiro.",
          "In the psalm pardon comes after saying: I did not hide my sin. The acknowledgement comes first.",
          pt_title="Não ocultei", en_title="I did not hide it",
          pt_saint="São Pedro e São Paulo", en_saint="Saints Peter and Paul",
          pt_why="Um negou Jesus três vezes e outro perseguiu a Igreja antes de Damasco; os dois são celebrados juntos em 29 de junho.",
          en_why="One denied Jesus three times and the other persecuted the Church before Damascus; both are celebrated together on 29 June.",
          pt_step="Escreva hoje, em uma frase, o que você tem evitado nomear.",
          en_step="Write down today, in one sentence, what you have been avoiding naming."),

        r("monica", (24, (7,)), (24, (7,)),
          "O pedido é para que Deus não se recorde dos pecados da mocidade: o salmo trata o passado como coisa que pode ser deixada.",
          "The request is that God not remember the sins of youth: the psalm treats the past as something that can be left.",
          pt_title="Os pecados da mocidade", en_title="The sins of my youth",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Segundo as Confissões, ela própria teve na juventude o hábito de beber vinho às escondidas, corrigido por uma serva.",
          en_why="According to the Confessions, in her youth she had the habit of drinking wine in secret, corrected by a servant.",
          pt_step="Pare hoje de contar uma história antiga sua em tom de piada.",
          en_step="Stop telling one old story of yours today as if it were a joke."),

        r("josefina-bakhita", (85, (5,)), (85, (5,)),
          "O salmo descreve Deus como cheio de misericórdia para todos os que o invocam, sem filtro de mérito.",
          "The psalm describes God as plenteous in mercy to all that call upon him, with no filter of merit.",
          pt_title="Cheio de misericórdia", en_title="Plenteous in mercy",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Disse dos que a escravizaram que, se os encontrasse, beijaria as mãos deles — registrado por quem a ouviu.",
          en_why="She said of those who enslaved her that if she met them she would kiss their hands — recorded by those who heard her.",
          pt_step="Reze hoje pelo nome de alguém que te fez mal.",
          en_step="Pray today by name for someone who wronged you."),

        r("rita-cassia", (102, (3,)), (102, (3,)),
          "Perdoar e sarar aparecem no mesmo versículo, como dois atos do mesmo sujeito.",
          "Forgiving and healing appear in the same verse, as two acts of the same subject.",
          pt_title="Perdoa e sara", en_title="Forgives and heals",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Perdoou publicamente os assassinos do marido e trabalhou para impedir a vingança dos filhos.",
          en_why="She publicly forgave her husband's murderers and worked to stop her sons from taking revenge.",
          pt_step="Não retribua hoje uma provocação que você poderia retribuir.",
          en_step="Do not return one provocation today that you could return."),

        r("inacio-loyola", (50, (19,)), (50, (19,)),
          "O sacrifício aceito no salmo é um espírito contrito: o que se oferece é o próprio reconhecimento.",
          "The sacrifice accepted in the psalm is an afflicted spirit: what is offered is the acknowledgement itself.",
          pt_title="Um espírito contrito", en_title="An afflicted spirit",
          pt_saint="Santo Inácio de Loyola", en_saint="Saint Ignatius of Loyola",
          pt_why="Fez uma confissão geral de três dias em Montserrat antes de deixar as armas no altar.",
          en_why="He made a three-day general confession at Montserrat before leaving his weapons at the altar.",
          pt_step="Reze hoje um ato de contrição devagar, uma frase por vez.",
          en_step="Pray an act of contrition today slowly, one line at a time."),

        r("agostinho", (37, (19,)), (37, (19,)),
          "Declarar a própria culpa e pensar nela são apresentados como ato de quem já confia no ouvinte.",
          "Declaring one's iniquity and thinking on it are presented as the act of one who already trusts the hearer.",
          pt_title="Eu confesso", en_title="I will declare",
          pt_saint="Santo Agostinho", en_saint="Saint Augustine",
          pt_why="Foi bispo de Hipona por mais de trinta anos e continuou a escrever revisões dos próprios livros até o fim.",
          en_why="He was bishop of Hippo for over thirty years and kept writing revisions of his own books to the end.",
          pt_step="Releia hoje um exame seu antigo e pare depois de ler.",
          en_step="Reread one of your old examens today and stop after reading."),

        r("catarina-siena", (78, (9,)), (78, (9,)),
          "O pedido é de perdão pela glória do nome de Deus, não pelo alívio de quem pede.",
          "The request is for pardon for the glory of God's name, not for the relief of the one asking.",
          pt_title="Pela glória do teu nome", en_title="For the glory of your name",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Insistia por carta que os pecados dos pastores fossem tratados de frente, dirigindo-se ao papa sem rodeios.",
          en_why="She insisted by letter that the sins of pastors be faced head on, addressing the pope without circumlocution.",
          pt_step="Peça perdão hoje sem explicar por que você fez.",
          en_step="Ask forgiveness today without explaining why you did it."),

        r("teresinha", (88, (34,)), (88, (34,)),
          "A promessa é de não retirar a graça: no salmo, o perdão é apresentado como fidelidade de Deus a si mesmo.",
          "The promise is not to take mercy away: in the psalm, pardon is God's fidelity to himself.",
          pt_title="Não retirarei a graça", en_title="My mercy I will not take away",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Comparou-se a uma criança pequena diante de uma escada alta, incapaz de subir e contando com ser carregada.",
          en_why="She compared herself to a small child before a tall staircase, unable to climb and counting on being carried.",
          pt_step="Pare hoje de pedir perdão pela mesma coisa outra vez.",
          en_step="Stop asking forgiveness today for the same thing again."),

        r("jose-sanchez-del-rio", (64, (4,)), (64, (4,)),
          "O salmo diz que os delitos nos oprimem e, no mesmo verso, que Deus os perdoa. A opressão não é a última palavra.",
          "The psalm says our sins press on us and, in the same verse, that God pardons them. The pressing is not the last word.",
          pt_title="Tu os perdoas", en_title="Thou wilt pardon them",
          pt_saint="São José Sánchez del Río", en_saint="Saint José Sánchez del Río",
          pt_why="Adolescente mexicano morto em 1928 na perseguição religiosa, depois de recusar renegar a fé.",
          en_why="A Mexican teenager killed in 1928 during the religious persecution, after refusing to renounce the faith.",
          pt_step="Faça hoje a coisa certa que você tem adiado por medo do que vão dizer.",
          en_step="Do the right thing today that you have been putting off for fear of what people will say."),

        r("oscar-romero", (105, (43,)), (105, (43,)),
          "O salmo conta que Deus livrou muitas vezes o mesmo povo que voltou a errar: a paciência é narrada, não afirmada.",
          "The psalm recounts that God delivered the same people many times over as they went wrong again: the patience is narrated, not asserted.",
          pt_title="Muitas vezes os livrou", en_title="Many times he delivered them",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Mudou de posição pública depois do assassinato do padre Rutilio Grande, em 1977, e passou a denunciar a repressão.",
          en_why="He changed his public stance after the murder of Father Rutilio Grande in 1977, and began denouncing the repression.",
          pt_step="Volte hoje a uma prática boa que você abandonou.",
          en_step="Return today to one good practice you abandoned."),

        r("vicente-paulo", (50, (3,)), (50, (3,)),
          "O Miserere mede o pedido pela misericórdia de Deus, não pelo tamanho da falta.",
          "The Miserere measures the request by God's mercy, not by the size of the fault.",
          pt_title="Segundo a tua misericórdia", en_title="According to your mercy",
          pt_saint="São Vicente de Paulo", en_saint="Saint Vincent de Paul",
          pt_why="Organizou missões para o interior da França e insistia que a caridade fosse feita com organização, não só com boa vontade.",
          en_why="He organized missions to rural France and insisted charity be done with organization, not goodwill alone.",
          pt_step="Repare hoje um dano concreto que você causou, mesmo pequeno.",
          en_step="Repair one concrete damage you caused today, however small."),
    ],

    "loved": [
        r("teresinha", (102, (13,)), (102, (13,)),
          "A comparação do salmo é com um pai que se compadece: a imagem é de proximidade, não de autoridade.",
          "The psalm's comparison is a father having compassion: the image is nearness, not authority.",
          pt_title="Como um pai", en_title="As a father",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Perdeu a mãe aos quatro anos e tinha no pai a figura sobre a qual escreveu ao falar de confiança.",
          en_why="She lost her mother at four, and her father was the figure she wrote about when speaking of confidence.",
          pt_step="Diga hoje a alguém da sua casa uma coisa que você gosta nele.",
          en_step="Tell someone in your home today one thing you like about them."),

        r("isabel-trindade", (138, (13,)), (138, (13,)),
          "O salmo fala de ter sido entretecido antes de nascer: o amor aqui antecede qualquer mérito possível.",
          "The psalm speaks of being knit before birth: the love here precedes any possible merit.",
          pt_title="Antes de eu nascer", en_title="Before I was born",
          pt_saint="Santa Isabel da Trindade", en_saint="Saint Elizabeth of the Trinity",
          pt_why="Escreveu que a alma é habitação da Trindade, e assinou-se \"Laudem Gloriae\", louvor de glória.",
          en_why="She wrote that the soul is a dwelling of the Trinity, and signed herself \"Laudem Gloriae\", praise of glory.",
          pt_step="Fique hoje dois minutos parado sem fazer nada útil.",
          en_step="Stay still for two minutes today doing nothing useful."),

        r("josefina-bakhita", (62, (4,)), (62, (4,)),
          "A graça é chamada melhor que a vida: o salmo põe o amor de Deus acima do próprio bem de existir.",
          "Mercy is called better than lives: the psalm sets God's love above the very good of existing.",
          pt_title="Melhor que a vida", en_title="Better than life",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Ao descobrir que tinha um dono que a amava, pediu o batismo e ficou com o nome Josefina em 1890.",
          en_why="On learning she had a master who loved her, she asked for baptism and took the name Josephine in 1890.",
          pt_step="Escreva hoje o seu nome de batismo e a data, se você souber.",
          en_step="Write down today your baptismal name and its date, if you know it."),

        r("jose", (21, (10,)), (21, (10,)),
          "O salmo diz que Deus foi guia desde o ventre materno: o cuidado começa antes da consciência dele.",
          "The psalm says God has been his guide from the womb: the care begins before any awareness of it.",
          pt_title="Desde o ventre", en_title="From the womb",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Levou a família ao Egito de noite, por aviso recebido em sonho, sem nenhuma palavra sua registrada nos Evangelhos.",
          en_why="He took the family into Egypt by night on a warning received in a dream, with no word of his own recorded in the Gospels.",
          pt_step="Faça hoje uma coisa por alguém sem que ele saiba que foi você.",
          en_step="Do one thing for someone today without their knowing it was you."),

        r("clara-assis", (35, (8,)), (35, (8,)),
          "\"Quão preciosa é a tua graça\" é dito com espanto: o salmo trata o amor recebido como surpresa, não como direito.",
          "\"How hast thou multiplied thy mercy\" is said in astonishment: the psalm treats love received as surprise, not entitlement.",
          pt_title="Quão preciosa", en_title="How precious",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Fugiu de casa na noite do Domingo de Ramos de 1212 para seguir a forma de vida de Francisco.",
          en_why="She left home on the night of Palm Sunday in 1212 to follow Francis's form of life.",
          pt_step="Agradeça hoje por uma coisa que você recebeu e não pediu.",
          en_step="Give thanks today for one thing you received and did not ask for."),

        r("joao-cruz", (85, (15,)), (85, (15,)),
          "Deus é descrito como lento para a ira: o salmo mede o amor divino pelo tempo que ele leva.",
          "God is described as patient: the psalm measures divine love by how long he takes.",
          pt_title="Lento para a ira", en_title="Patient and merciful",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Depois de ser preso pelos próprios irmãos de ordem, voltou a conviver com eles e assumiu cargos de governo.",
          en_why="After being imprisoned by his own brothers in religion, he went back to living among them and took up posts of governance.",
          pt_step="Dê hoje mais tempo a uma pessoa que te irrita.",
          en_step="Give more time today to a person who irritates you."),

        r("carlo-acutis", (116, (2,)), (116, (2,)),
          "O salmo mais curto do Saltério diz apenas que a misericórdia foi confirmada sobre nós, e para.",
          "The shortest psalm in the Psalter says only that his mercy is confirmed upon us, and stops.",
          pt_title="Confirmada sobre nós", en_title="Confirmed upon us",
          pt_saint="São Carlo Acutis", en_saint="Saint Carlo Acutis",
          pt_why="Chamava a Eucaristia de sua \"autoestrada para o céu\", frase registrada por quem o conheceu.",
          en_why="He called the Eucharist his \"highway to heaven\", a phrase recorded by those who knew him.",
          pt_step="Vá hoje à Missa num dia que não é domingo.",
          en_step="Go to Mass today on a day that is not Sunday."),

        r("damiao-molokai", (67, (7,)), (67, (7,)),
          "Deus é apresentado preparando casa para os desamparados: o amor do salmo tem forma de moradia.",
          "God is shown making a home for the forsaken: the psalm's love has the shape of a dwelling.",
          pt_title="Casa para os desamparados", en_title="A house for the forsaken",
          pt_saint="São Damião de Molokai", en_saint="Saint Damien of Molokai",
          pt_why="Pediu para ser enviado a Molokai quando os superiores buscavam voluntários, e nunca pediu para sair.",
          en_why="He asked to be sent to Molokai when his superiors sought volunteers, and never asked to leave.",
          pt_step="Convide alguém para comer na sua casa esta semana.",
          en_step="Invite someone to eat at your home this week."),

        r("monica", (41, (9,)), (41, (9,)),
          "O salmo divide o dia: de dia a graça, de noite o cântico. O amor aparece como companhia contínua.",
          "The psalm divides the day: by day his mercy, by night a canticle. The love appears as continuous company.",
          pt_title="De dia e de noite", en_title="By day and by night",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Rezou pelo filho por quase trinta anos, e é lembrada pela resposta de um bispo: o filho de tantas lágrimas não se perderia.",
          en_why="She prayed for her son for nearly thirty years, and is remembered for a bishop's reply: the son of so many tears would not be lost.",
          pt_step="Reze hoje por alguém à noite, antes de dormir, em vez de pela manhã.",
          en_step="Pray for someone tonight before sleeping, instead of in the morning."),

        r("rita-cassia", (30, (20,)), (30, (20,)),
          "A bondade é dita reservada, guardada para quem teme a Deus: no salmo o amor tem depósito.",
          "The sweetness is said to be laid up, kept for those who fear God: in the psalm the love is stored.",
          pt_title="Bondade reservada", en_title="Sweetness laid up",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Foi recusada três vezes pelo mosteiro de Cássia antes de ser aceita, já viúva e sem os filhos.",
          en_why="She was refused three times by the monastery at Cascia before being accepted, already widowed and without her sons.",
          pt_step="Insista hoje numa coisa boa que já te foi negada uma vez.",
          en_step="Try again today at one good thing you were once refused."),

        r("maximiliano-kolbe", (88, (2,)), (88, (2,)),
          "O salmista promete cantar as graças eternamente: o amor recebido gera obrigação de anunciar, não de retribuir.",
          "The psalmist promises to sing his mercies for ever: love received creates a duty to proclaim, not to repay.",
          pt_title="Cantarei eternamente", en_title="I will sing for ever",
          pt_saint="São Maximiliano Maria Kolbe", en_saint="Saint Maximilian Kolbe",
          pt_why="Fundou uma editora e uma cidade religiosa na Polônia antes de morrer no bunker da fome em Auschwitz, em 1941.",
          en_why="He founded a press and a religious city in Poland before dying in the starvation bunker at Auschwitz in 1941.",
          pt_step="Conte hoje a alguém por que você reza, sem argumentar.",
          en_step="Tell someone today why you pray, without arguing."),

        r("vicente-paulo", (106, (8,)), (106, (8,)),
          "O salmo manda dar graças pela misericórdia e pelas maravilhas: as duas coisas na mesma frase, uma explicando a outra.",
          "The psalm bids us give glory for his mercies and his wonderful works: both in one line, one explaining the other.",
          pt_title="Pela sua misericórdia", en_title="For his mercies",
          pt_saint="São Vicente de Paulo", en_saint="Saint Vincent de Paul",
          pt_why="Foi ele mesmo capturado por corsários na juventude, segundo carta atribuída a ele, antes de dedicar-se aos pobres.",
          en_why="He was himself taken by corsairs in his youth, according to a letter attributed to him, before devoting himself to the poor.",
          pt_step="Dê hoje uma quantia que você vá sentir falta.",
          en_step="Give away today an amount you will actually miss."),

        r("andre-bessette", (102, (17,)), (102, (17,)),
          "A misericórdia é dita estendida de eternidade a eternidade: o salmo mede o amor por duração, não por intensidade.",
          "The mercy is said to be from eternity unto eternity: the psalm measures love by duration, not by intensity.",
          pt_title="De eternidade a eternidade", en_title="From eternity to eternity",
          pt_saint="Santo André Bessette", en_saint="Saint André Bessette",
          pt_why="Recebeu visitantes na portaria do Colégio Notre-Dame em Montreal durante quarenta anos, um por um.",
          en_why="He received visitors at the door of Notre-Dame College in Montreal for forty years, one at a time.",
          pt_step="Ouça hoje uma pessoa até ela terminar de falar.",
          en_step="Listen to one person today until they finish speaking."),

        r("francisco-assis", (32, (5,)), (32, (5,)),
          "A terra é dita cheia da graça do Senhor: o amor, no salmo, está distribuído no mundo criado.",
          "The earth is said to be full of the mercy of the Lord: in the psalm, love is spread through the created world.",
          pt_title="A terra cheia de graça", en_title="The earth full of mercy",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Chamou de irmãos o sol, a água e o fogo no Cântico das Criaturas, e de irmã a própria morte.",
          en_why="He called sun, water and fire brothers in the Canticle of the Creatures, and death itself a sister.",
          pt_step="Coma hoje uma refeição devagar, prestando atenção no que é.",
          en_step="Eat one meal today slowly, paying attention to what it is."),

        r("edith-stein", (44, (12,)), (44, (12,)),
          "O salmo fala de um rei que deseja a beleza de quem o segue: o amor é apresentado como escolha dele, não conquista dela.",
          "The psalm speaks of a king who desires the beauty of the one who follows him: love is presented as his choice, not her achievement.",
          pt_title="Ele desejará", en_title="He shall desire",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Doutorou-se em filosofia quando poucas mulheres o faziam, e depois pediu a entrada no Carmelo.",
          en_why="She earned a doctorate in philosophy when few women did, and afterwards asked to enter Carmel.",
          pt_step="Aceite hoje um convite que você ia recusar por se achar pouco.",
          en_step="Accept one invitation today that you were going to refuse out of feeling unworthy."),
    ],
}
