# -*- coding: utf-8 -*-
"""Bloco 4 — steadfast (consolação) e empty (desolação)."""

from exam_relief_content._shared import r

BLOCK = {
    "steadfast": [
        r("benito", (111, (7,)), (111, (7,)),
          "O coração firme do salmo é descrito pelo que não faz: não teme as notícias que vierem.",
          "The psalm describes the steady heart by what it does not do: it does not fear the tidings that come.",
          pt_title="O coração firme", en_title="A heart that stands",
          pt_saint="São Bento", en_saint="Saint Benedict",
          pt_why="Pôs a estabilidade entre os votos do monge: comprometer-se com um lugar e um grupo, não só com um ideal.",
          en_why="He put stability among the monk's vows: binding oneself to one place and one group, not only to an ideal.",
          pt_step="Cumpra hoje um compromisso do qual você já quis desistir.",
          en_step="Keep one commitment today that you have already wanted to drop."),

        r("maximiliano-kolbe", (26, (3,)), (26, (3,)),
          "O salmo imagina exércitos acampados e mantém o coração sem temor: a firmeza é medida contra o cerco.",
          "The psalm pictures armies in camp and keeps the heart unafraid: steadiness is measured against a siege.",
          pt_title="Ainda que acampem exércitos", en_title="Though armies encamp",
          pt_saint="São Maximiliano Maria Kolbe", en_saint="Saint Maximilian Kolbe",
          pt_why="Deu-se como substituto de um condenado à morte em Auschwitz e sobreviveu duas semanas no bunker da fome.",
          en_why="He gave himself in place of a man condemned to death at Auschwitz and survived two weeks in the starvation bunker.",
          pt_step="Diga hoje um \"não\" que você tem medo de dizer.",
          en_step="Say one \"no\" today that you are afraid to say."),

        r("teresa-avila", (15, (8,)), (15, (8,)),
          "A firmeza vem de um gesto repetido: pôr o Senhor sempre diante de si. É prática, não temperamento.",
          "The steadiness comes from a repeated gesture: setting the Lord always in one's sight. Practice, not temperament.",
          pt_title="Sempre diante de mim", en_title="Always in my sight",
          pt_saint="Santa Teresa de Ávila", en_saint="Saint Teresa of Ávila",
          pt_why="Fundou dezessete mosteiros viajando em carro de bois pela Espanha, enfrentando oposição dentro da própria ordem.",
          en_why="She founded seventeen monasteries travelling by ox-cart across Spain, facing opposition within her own order.",
          pt_step="Repita hoje, três vezes, a mesma oração curta em horas marcadas.",
          en_step="Repeat the same short prayer three times today, at set hours."),

        r("edith-stein", (124, (1,)), (124, (1,)),
          "A comparação é com um monte: não é rigidez, é peso assentado. O salmo descreve estabilidade, não tensão.",
          "The comparison is a mountain: not rigidity, but settled weight. The psalm describes stability, not tension.",
          pt_title="Firmes como o monte", en_title="As mount Sion",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Foi levada de um convento na Holanda em 1942 junto de outros católicos de origem judia, e morreu em Auschwitz.",
          en_why="She was taken from a convent in the Netherlands in 1942 along with other Catholics of Jewish origin, and died at Auschwitz.",
          pt_step="Fique hoje onde você está, mesmo querendo sair.",
          en_step="Stay where you are today, even wanting to leave."),

        r("francisco-xavier", (36, (23,)), (36, (23,)),
          "Os passos são firmados por Deus: a firmeza do salmo é sobre a direção, não sobre a força de quem anda.",
          "The steps are directed by the Lord: the psalm's steadiness is about direction, not about the walker's strength.",
          pt_title="Os passos firmados", en_title="Steps directed",
          pt_saint="São Francisco Xavier", en_saint="Saint Francis Xavier",
          pt_why="Percorreu a Índia, as Molucas e o Japão em dez anos de viagens, morrendo às portas da China em 1552.",
          en_why="He crossed India, the Moluccas and Japan in ten years of travel, dying at the gates of China in 1552.",
          pt_step="Dê hoje um passo pequeno num plano que você só pensa.",
          en_step="Take one small step today on a plan you only ever think about."),

        r("tomas-aquino", (118, (89,)), (118, (89,)),
          "A estabilidade é da palavra de Deus, não do salmista: ele se apoia no que permanece fora dele.",
          "The firmness belongs to God's word, not to the psalmist: he leans on what stands outside himself.",
          pt_title="Permanece a tua palavra", en_title="Your word stands firm",
          pt_saint="São Tomás de Aquino", en_saint="Saint Thomas Aquinas",
          pt_why="Escreveu sobre objeções antes de responder a elas, apresentando o argumento contrário no melhor formato possível.",
          en_why="He set out objections before answering them, presenting the opposing argument in its strongest form.",
          pt_step="Leia hoje um argumento contra o que você pensa, até o fim.",
          en_step="Read one argument against your own view today, to the end."),

        r("oscar-romero", (55, (5,)), (55, (5,)),
          "A confiança é declarada com o temor ainda presente: o salmo não pede que ele desapareça primeiro.",
          "Trust is declared with the fear still present: the psalm does not ask it to go away first.",
          pt_title="Em Deus confio", en_title="In God I have trusted",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Continuou a pregar contra a repressão depois de receber ameaças de morte, e foi morto celebrando a Missa.",
          en_why="He kept preaching against the repression after receiving death threats, and was killed while celebrating Mass.",
          pt_step="Faça hoje a coisa certa antes de se sentir pronto.",
          en_step="Do the right thing today before you feel ready."),

        r("padre-pio", (61, (3,)), (61, (3,)),
          "O salmo chama Deus de baluarte e conclui que não haverá queda: a firmeza é consequência, não esforço.",
          "The psalm calls God a protector and concludes there will be no falling: steadiness is a consequence, not an effort.",
          pt_title="O meu baluarte", en_title="My protector",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Aceitou sem recurso público as restrições que a Santa Sé lhe impôs e continuou no mesmo convento.",
          en_why="He accepted without public appeal the restrictions the Holy See imposed on him and stayed in the same friary.",
          pt_step="Aceite hoje uma correção sem se defender.",
          en_step="Accept one correction today without defending yourself."),

        r("joao-paulo-ii", (90, (11,)), (90, (11,)),
          "A guarda prometida é para os caminhos, não contra eles: o salmo supõe que se vai andar.",
          "The keeping promised is for the ways, not against them: the psalm assumes you will walk.",
          pt_title="Nos teus caminhos", en_title="In all thy ways",
          pt_saint="São João Paulo II", en_saint="Saint John Paul II",
          pt_why="Voltou a trabalhar depois do atentado de 1981 e mais tarde visitou na prisão o homem que atirou nele.",
          en_why="He went back to work after the 1981 attempt on his life, and later visited in prison the man who shot him.",
          pt_step="Vá hoje a um lugar que você tem evitado.",
          en_step="Go today to one place you have been avoiding."),

        r("catarina-siena", (17, (33,)), (17, (33,)),
          "É Deus quem reveste de força no salmo: a firmeza é descrita como roupa dada, não músculo próprio.",
          "It is God who girds with strength in the psalm: steadiness is described as clothing given, not muscle of one's own.",
          pt_title="Revestido de força", en_title="Girt with strength",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Cuidou de doentes na peste de Siena e ao mesmo tempo mantinha correspondência política sem nenhum cargo.",
          en_why="She nursed the sick in the Siena plague while keeping up political correspondence holding no office.",
          pt_step="Peça hoje força para uma coisa específica, nomeando-a.",
          en_step="Ask today for strength for one specific thing, naming it."),

        r("josefina-bakhita", (39, (3,)), (39, (3,)),
          "O salmo descreve ter sido tirado do lodo e assentado: a firmeza atual é memória de um resgate.",
          "The psalm describes being drawn from the mire and set firm: present steadiness is the memory of a rescue.",
          pt_title="Assentado na rocha", en_title="Set upon a rock",
          pt_saint="Santa Josefina Bakhita", en_saint="Saint Josephine Bakhita",
          pt_why="Foi declarada livre por um tribunal italiano em 1889 e escolheu ficar com as canossianas.",
          en_why="She was declared free by an Italian court in 1889 and chose to stay with the Canossians.",
          pt_step="Conte hoje a si mesmo, por escrito, de onde você já saiu.",
          en_step="Write down for yourself today what you have already come out of."),

        r("jose", (36, (23,)), (72, (23,)),
          "Estar sempre com Deus é dito logo depois do desabafo: o salmo admite a queixa e mantém a companhia.",
          "Being always with God is said right after the complaint: the psalm admits the grievance and keeps the company.",
          pt_title="Firmado no que faço", en_title="Always with you",
          pt_saint="São José", en_saint="Saint Joseph",
          pt_why="Trabalhou como carpinteiro em Nazaré, e os Evangelhos não lhe atribuem nenhuma palavra.",
          en_why="He worked as a carpenter in Nazareth, and the Gospels attribute no word to him.",
          pt_step="Faça hoje bem feito o trabalho que ninguém vai conferir.",
          en_step="Do well today the work no one will check."),

        r("damiao-molokai", (20, (8,)), (20, (8,)),
          "A confiança do salmo é dita de um rei — alguém com poder — e mesmo assim apoiada fora de si.",
          "The psalm's trust is said of a king — someone with power — and even so it leans outside himself.",
          pt_title="Confia no Senhor", en_title="He hopes in the Lord",
          pt_saint="São Damião de Molokai", en_saint="Saint Damien of Molokai",
          pt_why="Continuou o trabalho em Molokai depois de saber que havia contraído a doença, e morreu lá em 1889.",
          en_why="He continued his work at Molokai after learning he had contracted the disease, and died there in 1889.",
          pt_step="Continue hoje uma coisa que você começou e ficou mais difícil.",
          en_step="Carry on today with something you began that has got harder."),

        r("rita-cassia", (124, (2,)), (124, (2,)),
          "A imagem é de cerco protetor: montes em volta de Jerusalém, e o Senhor em volta do povo.",
          "The image is a protective ring: mountains around Jerusalem, and the Lord around his people.",
          pt_title="Circundado", en_title="Round about",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Permaneceu quarenta anos no mosteiro de Cássia, os últimos deles com uma ferida na fronte que não sarava.",
          en_why="She remained forty years in the monastery at Cascia, her last ones with a wound on her forehead that would not heal.",
          pt_step="Peça hoje a alguém que reze por você, dizendo pelo quê.",
          en_step="Ask someone today to pray for you, saying what for."),

        r("luis-gonzaga", (61, (7,)), (61, (6,)),
          "A alma é mandada repousar em Deus e o salmo repete que não haverá queda: a ordem é interior.",
          "The soul is told to rest in God and the psalm repeats there will be no falling: the command is inward.",
          pt_title="Não serei abalado", en_title="I shall not be moved",
          pt_saint="São Luís Gonzaga", en_saint="Saint Aloysius Gonzaga",
          pt_why="Insistiu em servir os doentes da peste romana de 1591 contra o conselho dos superiores, e contraiu a doença.",
          en_why="He insisted on serving the sick in the Roman plague of 1591 against his superiors' advice, and caught the disease.",
          pt_step="Mantenha hoje o horário de dormir que você decidiu.",
          en_step="Keep today the bedtime you decided on."),
    ],

    "empty": [
        r("joao-cruz", (41, (3,)), (41, (3,)),
          "A sede do salmo é por Deus vivo, e vem com uma pergunta: quando. O vazio aqui é espera, não ausência.",
          "The psalm's thirst is for the living God, and comes with a question: when. The emptiness here is waiting, not absence.",
          pt_title="Sede de Deus vivo", en_title="Thirst for the living God",
          pt_saint="São João da Cruz", en_saint="Saint John of the Cross",
          pt_why="Deu nome de noite escura ao estado em que a oração não sente nada, tratando-o como passagem e não como falha.",
          en_why="He named as dark night the state in which prayer feels nothing, treating it as a passage and not a failure.",
          pt_step="Reze hoje o tempo que você marcou, mesmo sem sentir.",
          en_step="Pray today for the time you set, even feeling nothing."),

        r("teresinha", (62, (2,)), (62, (2,)),
          "O salmista busca de madrugada, antes de qualquer resposta: o vazio é tratado como hora de procurar.",
          "The psalmist watches at break of day, before any answer: the emptiness is treated as the hour to seek.",
          pt_title="Desde a madrugada", en_title="At break of day",
          pt_saint="Santa Teresinha do Menino Jesus", en_saint="Saint Thérèse of the Child Jesus",
          pt_why="Descreveu os últimos meses como uma parede erguida até o céu, e continuou a rezar sem consolo.",
          en_why="She described her last months as a wall raised to the sky, and kept praying without consolation.",
          pt_step="Comece hoje o dia com uma frase de oração antes de tudo.",
          en_step="Begin today with one line of prayer before anything else."),

        r("agostinho", (41, (2,)), (41, (2,)),
          "A comparação é com a cerva que suspira pelas fontes: o vazio é desejo com direção, não falta de tudo.",
          "The comparison is the hart panting for the water springs: the emptiness is desire with direction, not absence of everything.",
          pt_title="Como a cerva", en_title="As the hart",
          pt_saint="Santo Agostinho", en_saint="Saint Augustine",
          pt_why="Descreveu anos de busca por escolas e seitas antes de Milão, nomeando cada caminho que tentou.",
          en_why="He described years of searching through schools and sects before Milan, naming each road he tried.",
          pt_step="Nomeie hoje em uma frase o que você está procurando.",
          en_step="Name in one sentence today what you are looking for."),

        r("edith-stein", (142, (6,)), (142, (6,)),
          "As mãos são estendidas e a alma comparada a terra sem água: o salmo dá forma corporal ao vazio.",
          "The hands are stretched out and the soul likened to waterless ground: the psalm gives the emptiness a bodily shape.",
          pt_title="Terra sem água", en_title="Earth without water",
          pt_saint="Santa Teresa Benedita da Cruz", en_saint="Saint Teresa Benedicta of the Cross",
          pt_why="Deixou a carreira acadêmica, ficou anos sem posto por ser judia, e depois entrou no Carmelo de Colônia.",
          en_why="She left her academic career, spent years without a post because she was Jewish, and then entered the Carmel of Cologne.",
          pt_step="Abra as mãos hoje ao rezar, mesmo sozinho.",
          en_step="Open your hands today while praying, even alone."),

        r("francisco-assis", (106, (9,)), (106, (9,)),
          "O salmo afirma que a alma faminta foi saciada: é dito no passado, como fato, não como promessa.",
          "The psalm states the empty soul has been satisfied: said in the past, as fact, not as promise.",
          pt_title="Saciou a alma faminta", en_title="He satisfied the empty soul",
          pt_saint="São Francisco de Assis", en_saint="Saint Francis of Assisi",
          pt_why="Trocou a herança do pai pela mendicância e dizia que a pobreza era escolha, não desgraça.",
          en_why="He traded his father's inheritance for begging and called poverty a choice, not a misfortune.",
          pt_step="Coma hoje uma refeição simples de propósito.",
          en_step="Eat one deliberately plain meal today."),

        r("monica", (87, (4,)), (87, (4,)),
          "O salmista diz que a alma está saturada de males: o vazio, aqui, é excesso — não falta.",
          "The psalmist says his soul is filled with evils: the emptiness here is excess — not lack.",
          pt_title="Saturado de males", en_title="Filled with evils",
          pt_saint="Santa Mônica", en_saint="Saint Monica",
          pt_why="Viveu um casamento difícil com um marido de temperamento violento, segundo o relato do próprio filho.",
          en_why="She lived a hard marriage to a man of violent temper, according to her own son's account.",
          pt_step="Tire hoje uma coisa da sua agenda, sem substituir.",
          en_step="Remove one thing from your schedule today, without replacing it."),

        r("carlo-acutis", (101, (5,)), (101, (5,)),
          "O coração é dito ressequido como erva queimada, e o salmista diz que esqueceu de comer. O vazio tem sintoma.",
          "The heart is called withered like smitten grass, and the psalmist says he forgot to eat. The emptiness has a symptom.",
          pt_title="Como erva ressequida", en_title="Withered like grass",
          pt_saint="São Carlo Acutis", en_saint="Saint Carlo Acutis",
          pt_why="Manteve rotina de Missa e adoração diárias durante os anos de escola, até a doença que o matou em 2006.",
          en_why="He kept a daily routine of Mass and adoration through his school years, until the illness that killed him in 2006.",
          pt_step="Faça hoje uma refeição sentado, sem telefone.",
          en_step="Eat one meal sitting down today, without your phone."),

        r("jose-sanchez-del-rio", (68, (4,)), (68, (4,)),
          "O salmista está cansado de gritar e a garganta enrouqueceu: o salmo registra o esgotamento de continuar pedindo.",
          "The psalmist is worn out with crying and his jaws are hoarse: the psalm records the exhaustion of going on asking.",
          pt_title="Cansado de gritar", en_title="Worn out with crying",
          pt_saint="São José Sánchez del Río", en_saint="Saint José Sánchez del Río",
          pt_why="Tinha catorze anos quando foi preso; segundo os relatos, escreveu à mãe antes de morrer dizendo que a veria no céu.",
          en_why="He was fourteen when he was taken; by the accounts, he wrote to his mother before dying that he would see her in heaven.",
          pt_step="Escreva hoje a alguém uma carta curta, à mão.",
          en_step="Write someone a short letter by hand today."),

        r("rita-cassia", (30, (13,)), (30, (13,)),
          "O salmista se diz esquecido dos corações, como um morto: o vazio é descrito como não ser lembrado.",
          "The psalmist says he is forgotten as one dead: the emptiness is described as not being remembered.",
          pt_title="Esquecido", en_title="Forgotten",
          pt_saint="Santa Rita de Cássia", en_saint="Saint Rita of Cascia",
          pt_why="Viveu os últimos anos em reclusão no mosteiro, com a ferida que a mantinha afastada da comunidade.",
          en_why="She spent her last years in seclusion in the monastery, with the wound that kept her apart from the community.",
          pt_step="Procure hoje alguém que ninguém procura.",
          en_step="Reach out today to someone nobody reaches out to."),

        r("joao-batista", (60, (3,)), (60, (3,)),
          "O clamor vem dos confins da terra e o coração desfalece: o salmo admite estar longe e clamar de lá.",
          "The cry comes from the ends of the earth as the heart faints: the psalm allows being far off and calling from there.",
          pt_title="Dos confins da terra", en_title="From the ends of the earth",
          pt_saint="São João Batista", en_saint="Saint John the Baptist",
          pt_why="Pregou no deserto, longe de Jerusalém, e mandou perguntar a Jesus da prisão se era ele quem havia de vir.",
          en_why="He preached in the desert, far from Jerusalem, and from prison sent to ask Jesus whether he was the one to come.",
          pt_step="Reze hoje de onde você está, sem esperar estar melhor.",
          en_step="Pray today from where you are, without waiting to be better."),

        r("padre-pio", (37, (7,)), (37, (7,)),
          "O salmista se diz encurvado e oprimido todo o dia: o vazio é durável, e o salmo não o abrevia.",
          "The psalmist says he is bowed down and miserable all the day: the emptiness lasts, and the psalm does not cut it short.",
          pt_title="Todo o dia", en_title="All the day",
          pt_saint="São Pio de Pietrelcina", en_saint="Saint Pius of Pietrelcina",
          pt_why="Viveu décadas com dores nas mãos e nos pés, e continuou a atender o confessionário todos os dias.",
          en_why="He lived decades with pain in his hands and feet, and kept to the confessional every day.",
          pt_step="Cumpra hoje uma obrigação pequena que você não quer cumprir.",
          en_step="Fulfil one small duty today that you do not want to fulfil."),

        r("catarina-siena", (72, (21,)), (72, (21,)),
          "O salmo fala de espírito exasperado e coração sentido: reconhece o estado antes de dizer qualquer coisa sobre ele.",
          "The psalm speaks of a heart inflamed and reins changed: it acknowledges the state before saying anything about it.",
          pt_title="O espírito exasperado", en_title="A heart inflamed",
          pt_saint="Santa Catarina de Sena", en_saint="Saint Catherine of Siena",
          pt_why="Escreveu sobre períodos em que não sentia nada na oração, mantendo a mesma disciplina de sempre.",
          en_why="She wrote about periods in which she felt nothing in prayer, keeping the same discipline as always.",
          pt_step="Conte hoje a um confessor ou a um amigo que você está vazio.",
          en_step="Tell a confessor or a friend today that you are empty."),

        r("clara-assis", (142, (4,)), (142, (4,)),
          "O espírito desfalece e o coração gela: o salmo usa duas imagens para o mesmo esvaziamento.",
          "The spirit faints and the heart is troubled: the psalm uses two images for the same emptying.",
          pt_title="O espírito desfalece", en_title="My spirit in anguish",
          pt_saint="Santa Clara de Assis", en_saint="Saint Clare of Assisi",
          pt_why="Ficou acamada os últimos vinte e sete anos de vida e continuou a governar o mosteiro nesse tempo.",
          en_why="She was bedridden the last twenty-seven years of her life and kept governing the monastery through them.",
          pt_step="Faça hoje deitado a oração que você não consegue fazer de pé.",
          en_step="Pray today lying down the prayer you cannot manage standing."),

        r("oscar-romero", (76, (3,)), (76, (3,)),
          "O salmista busca a Deus no dia da angústia com a mão estendida: buscar é apresentado como o que se faz no vazio.",
          "The psalmist sought God in the day of his trouble with hands lifted up: seeking is what the psalm does with emptiness.",
          pt_title="No dia da angústia", en_title="In the day of trouble",
          pt_saint="São Óscar Romero", en_saint="Saint Óscar Romero",
          pt_why="Passou a ler publicamente, nas homilias transmitidas por rádio, os nomes dos desaparecidos da semana.",
          en_why="In homilies broadcast by radio he began reading out publicly the names of the week's disappeared.",
          pt_step="Reze hoje em voz alta o nome de alguém que sofre.",
          en_step="Say out loud in prayer today the name of someone who suffers."),

        r("andre-bessette", (21, (15,)), (21, (15,)),
          "O salmo diz derramar-se como água e ter os ossos desconjuntados: é o vazio descrito por dentro do corpo.",
          "The psalm speaks of being poured out like water with bones scattered: the emptiness described from inside the body.",
          pt_title="Derramado como água", en_title="Poured out like water",
          pt_saint="Santo André Bessette", en_saint="Saint André Bessette",
          pt_why="Tinha saúde frágil a vida inteira e sobreviveu à maioria dos que duvidaram que ele fosse aceito na congregação.",
          en_why="He had frail health all his life and outlived most of those who doubted he would be accepted into his congregation.",
          pt_step="Descanse hoje antes de estar exausto.",
          en_step="Rest today before you are exhausted."),
    ],
}
